A = "[ADULTO] "
P = [
# ---------------- VEÍCULOS (c=0) ----------------
dict(n=1, t="Carro de Corrida Turbo", c=0, i="3+", tm="30 min", d=1,
 mat=["1 caixa de sapato", "4 tampas de pote iguais", "2 palitos de churrasco sem ponta", "1 rolo de papel higiênico", "Tinta guache e pincel", "Cola quente (uso do adulto)"],
 pec=["Abertura do cockpit de 10 x 8 cm na tampa da caixa", "4 rodas de 6 cm (use as tampas de pote)", "1 volante de 5 cm (contorne uma tampinha grande)", "Número do carro num círculo de 7 cm de papel branco"],
 pas=["Feche a caixa de sapato e prenda a tampa com fita crepe.", A+"Recorte a abertura do cockpit no meio da tampa com estilete.", A+"Faça 2 furos de cada lado da caixa, na altura das rodas, e atravesse os palitos.", "Pinte a caixa com a cor preferida da criança e espere secar.", A+"Cole as tampas de pote nas pontas dos palitos com cola quente.", "Cole o rolo de papel na traseira como escapamento e o volante dentro do cockpit.", "Desenhe o número, faróis e listras de corrida com canetinha."],
 brinca="Monte uma pista com fita crepe no chão e faça uma corrida com os bonecos pilotando.",
 apr="Coordenação motora fina, cores e números."),
dict(n=2, t="Caminhão de Bombeiros Resgate", c=0, i="4+", tm="45 min", d=2,
 mat=["1 caixa de sapato", "1 caixa de leite vazia e lavada", "6 tampinhas pretas ou tampas de pote", "2 palitos de picolé", "4 palitos de fósforo usados ou canudos", "Tinta guache vermelha", "Cola branca e cola quente"],
 pec=["Escada: 2 palitos de picolé + 4 pedaços de canudo de 4 cm", "2 janelas de 5 x 4 cm de papel azul", "Sirene: 1 retângulo de 3 x 2 cm de papel azul ou vermelho", "6 rodas de 5 cm"],
 pas=["Cole a caixa de leite deitada na frente da caixa de sapato: ela vira a cabine.", "Pinte tudo de vermelho e deixe secar.", "Monte a escada colando os pedacinhos de canudo entre os dois palitos de picolé.", "Cole a escada em cima da carroceria, um pouco inclinada.", "Cole as janelas na cabine e a sirene no teto.", A+"Cole as 6 rodas com cola quente, 2 na cabine e 4 na carroceria.", "Desenhe uma mangueira enrolada com barbante ou canetinha na lateral."],
 brinca="Coloque um bichinho de pelúcia em cima do sofá e faça o resgate com o caminhão.",
 apr="Faz de conta, noção de profissões e ajuda ao próximo."),
dict(n=3, t="Ônibus Escolar Amarelinho", c=0, i="3+", tm="40 min", d=1,
 mat=["1 caixa de sapato comprida", "4 tampas de garrafa PET pretas", "Tinta guache amarela", "Papel branco", "Canetinhas", "Cola branca"],
 pec=["8 janelas de 4 x 3 cm de papel branco", "1 porta de 4 x 7 cm", "1 para-brisa de 10 x 4 cm", "1 placa de 6 x 2 cm escrita ESCOLAR"],
 pas=["Feche a caixa e prenda a tampa com fita crepe.", "Pinte a caixa toda de amarelo e deixe secar bem.", "Recorte as janelas e desenhe um passageiro diferente em cada uma (família, amigos, bichinhos).", "Cole as janelas enfileiradas dos dois lados.", "Cole a porta, o para-brisa e a placa na frente.", "Cole as tampinhas como rodas.", "Faça uma faixa preta de canetinha no meio de toda a lateral."],
 brinca="Brinque de levar os brinquedos para a escola: pare nos 'pontos' espalhados pela casa.",
 apr="Criatividade no desenho, rotina e contagem de passageiros."),
dict(n=4, t="Trator da Fazenda", c=0, i="4+", tm="40 min", d=2,
 mat=["1 caixa de creme dental ou caixa pequena", "1 caixa de leite", "2 tampas de pote grandes", "2 tampinhas de garrafa", "1 rolo de papel higiênico", "Tinta verde ou vermelha", "Cola quente (uso do adulto)"],
 pec=["Cabine: janela de 5 x 5 cm recortada na caixa de leite", "2 rodas grandes de 9 cm (tampas de pote)", "2 rodas pequenas de 3 cm (tampinhas)", "Chaminé: 1 pedaço de rolo de 4 cm"],
 pas=["Deite a caixa de creme dental: ela é o capô.", A+"Corte a caixa de leite ao meio e recorte a janela da cabine.", "Cole a cabine atrás do capô, em pé.", "Pinte tudo e espere secar.", A+"Cole as rodas grandes atrás e as pequenas na frente com cola quente.", "Cole a chaminé em cima do capô.", "Faça os detalhes: faróis, grade do motor e um volante de tampinha."],
 brinca="Faça uma 'plantação' de tampinhas no tapete e use o trator para colher e levar até o celeiro.",
 apr="Tamanhos (grande e pequeno), vida no campo e origem dos alimentos."),
dict(n=5, t="Caminhão de Lixo Recicla", c=0, i="4+", tm="45 min", d=2,
 mat=["2 caixas de sapato (ou 1 caixa de sapato e 1 caixa de leite)", "6 tampinhas", "Barbante", "Tinta verde", "Papel colorido (azul, vermelho, amarelo, verde)", "Cola"],
 pec=["Caçamba: tampa da caixa como porta traseira, presa com fita crepe na parte de cima", "4 quadrados de 3 x 3 cm nas cores da reciclagem", "6 rodas de 5 cm"],
 pas=["Cole a caixa menor na frente da maior para fazer a cabine.", "Pinte de verde e deixe secar.", "Prenda a tampa na traseira com fita crepe, como uma dobradiça: ela abre e fecha.", "Cole os quadradinhos coloridos na lateral e escreva: papel, plástico, metal e vidro.", "Cole as rodas e desenhe as janelas da cabine.", "Faça bolinhas de papel coloridas para serem o 'lixo'."],
 brinca="Espalhe bolinhas coloridas pela sala; a criança recolhe e separa cada cor na lixeira certa.",
 apr="Reciclagem, separação por cores e cuidado com o planeta."),
dict(n=6, t="Ambulância Socorro Rápido", c=0, i="3+", tm="35 min", d=1,
 mat=["1 caixa de sapato", "1 caixa de leite", "4 tampinhas pretas", "Tinta branca", "Papel vermelho e azul", "Cola"],
 pec=["2 cruzes vermelhas: 2 retângulos de 6 x 2 cm cada, colados em X de 'mais'", "Sirene: 2 retângulos de 2 x 1,5 cm (1 azul e 1 vermelho)", "Portas traseiras: 2 retângulos de 5 x 7 cm"],
 pas=["Cole a caixa de leite deitada na frente da caixa de sapato (cabine).", "Pinte tudo de branco. Se precisar, passe duas demãos.", "Monte as cruzes vermelhas e cole uma de cada lado.", "Cole a sirene no teto da cabine.", "Desenhe as portas traseiras e escreva AMBULÂNCIA na frente.", "Cole as rodas."],
 brinca="Brinque de hospital: os bonecos 'machucados' são levados de ambulância para a enfermaria da caixa de sapato.",
 apr="Empatia, cuidado e reconhecimento de profissões."),
dict(n=7, t="Viatura de Polícia", c=0, i="3+", tm="35 min", d=1,
 mat=["1 caixa de sapato", "4 tampinhas pretas", "Tinta preta e branca", "Papel azul e vermelho", "Papel alumínio", "Cola"],
 pec=["Giroflex: 2 quadrados de 2 x 2 cm (1 azul e 1 vermelho)", "4 janelas de 5 x 3 cm", "2 faróis de 2 cm de papel alumínio", "Distintivo: 1 estrela de 5 cm de papel amarelo"],
 pas=["Feche a caixa e prenda a tampa.", "Pinte a metade de baixo de preto e a de cima de branco.", "Cole as janelas nas laterais.", "Cole o giroflex no teto e os faróis na frente.", "Cole a estrela nas portas e escreva POLÍCIA.", "Cole as rodas."],
 brinca="Brinque de trânsito: a viatura ajuda os carrinhos a atravessar e organiza a fila.",
 apr="Regras, segurança no trânsito e faz de conta."),
dict(n=8, t="Trem com 3 Vagões", c=0, i="4+", tm="60 min", d=2,
 mat=["4 caixas de leite ou caixinhas de suco", "1 rolo de papel higiênico", "16 tampinhas", "Barbante", "Tintas coloridas", "Cola quente (uso do adulto)"],
 pec=["Chaminé: rolo de papel higiênico cortado em 5 cm", "Janela da locomotiva: 4 x 4 cm", "Vagões abertos: recorte o topo de 3 caixas", "16 rodas de 3 cm (tampinhas)"],
 pas=["A primeira caixa, inteira e deitada, é a locomotiva. Cole a chaminé na frente.", A+"Recorte o topo das outras 3 caixas para virarem vagões abertos.", "Pinte cada vagão de uma cor.", A+"Cole 4 tampinhas em cada caixa com cola quente.", A+"Faça um furinho na frente e atrás de cada vagão.", "Passe o barbante e dê nós para ligar os vagões.", "Coloque brinquedos pequenos dentro dos vagões."],
 brinca="Faça uma viagem pela casa puxando o trem e 'entregando' carga em cada cômodo.",
 apr="Sequência, cores e contagem (quantos passageiros em cada vagão?)."),
dict(n=9, t="Moto Veloz", c=0, i="5+", tm="40 min", d=2,
 mat=["1 caixa de creme dental", "2 CDs velhos ou tampas de pote de 8 cm", "1 canudo", "1 rolo de papel higiênico", "Tinta e papel alumínio", "Cola quente (uso do adulto)"],
 pec=["Guidão: canudo de 10 cm", "Banco: retângulo de 7 x 3 cm de EVA preto", "Farol: círculo de 3 cm de papel alumínio", "2 rodas de 8 cm"],
 pas=["Pinte a caixa de creme dental com a cor da moto.", A+"Corte o rolo ao meio no comprimento e cole embaixo da caixa (suporte das rodas).", A+"Cole as rodas na frente e atrás com cola quente.", "Cole o banco em cima da caixa.", "Cole o guidão atravessado na frente.", "Cole o farol e desenhe os detalhes do motor."],
 brinca="Faça uma corrida de motos entre bonecos, com largada e bandeira quadriculada de papel.",
 apr="Coordenação e noção de velocidade (rápido e devagar)."),
dict(n=10, t="Escavadeira com Pá que Mexe", c=0, i="6+", tm="60 min", d=3,
 mat=["1 caixa de sapato pequena", "1 caixa de leite", "2 palitos de picolé", "1 copo descartável", "2 grampos bailarina (colchetes)", "Tinta amarela", "Cola quente (uso do adulto)"],
 pec=["Braço: 2 tiras de papelão de 15 x 3 cm", "Pá: meio copo descartável", "Esteiras: 2 tiras de papelão de 20 x 4 cm dobradas em volta da base", "Cabine: janela de 5 x 5 cm"],
 pas=["Cole a caixa de leite em pé em cima da caixa de sapato (cabine).", "Pinte tudo de amarelo e deixe secar.", A+"Faça furos nas pontas das tiras do braço e una com um grampo bailarina: vira uma articulação.", A+"Prenda o braço na lateral da cabine com o outro grampo.", A+"Cole o meio copo na ponta do braço como pá.", "Cole as tiras das esteiras nas laterais da base e desenhe os detalhes.", "Teste: o braço sobe e desce!"],
 brinca="Encha uma bacia com feijão ou arroz cru e brinque de cavar e transportar.",
 apr="Engenharia simples (articulação), força e motricidade."),
# ---------------- CÉU E ESPAÇO (c=1) ----------------
dict(n=11, t="Foguete Rumo à Lua", c=1, i="3+", tm="30 min", d=1,
 mat=["1 rolo de papel toalha", "1 folha de papel colorido", "Papelão fino (caixa de cereal)", "Papel alumínio", "Papel celofane laranja ou vermelho", "Cola"],
 pec=["Cone do nariz: meio círculo de 12 cm de diâmetro enrolado", "3 aletas: triângulos de 7 x 6 cm de papelão", "2 janelas redondas de 3 cm", "Chamas: 3 tiras de celofane de 10 x 3 cm"],
 pas=["Cubra o rolo com papel alumínio ou pinte da cor preferida.", "Enrole o meio círculo em cone e cole na ponta de cima.", A+"Faça 3 cortes de 3 cm na base do rolo.", "Encaixe as aletas nos cortes e passe cola.", "Cole as janelas e desenhe astronautas dentro.", "Cole as tiras de celofane saindo da base como fogo."],
 brinca="Faça a contagem regressiva '10, 9, 8…' e decole o foguete pela casa até a 'Lua' (uma almofada).",
 apr="Contagem regressiva, formas geométricas (cone e triângulo) e curiosidade sobre o espaço."),
dict(n=12, t="Avião Voa Longe", c=1, i="4+", tm="35 min", d=2,
 mat=["1 rolo de papel toalha", "Papelão fino", "1 palito de picolé", "1 tampinha", "1 grampo bailarina", "Tintas", "Cola quente (uso do adulto)"],
 pec=["Asa: retângulo de 25 x 5 cm com as pontas arredondadas", "Cauda: 1 retângulo de 10 x 3 cm e 1 triângulo de 5 x 5 cm", "Hélice: 1 palito de picolé", "Janelinhas: 6 círculos de 1,5 cm"],
 pas=["Pinte o rolo e a asa.", A+"Faça um corte de 5 cm atravessando o rolo, no meio, e encaixe a asa.", A+"Faça cortes na traseira e encaixe as peças da cauda (a horizontal e o triângulo em pé).", A+"Prenda a hélice na tampinha com o grampo e cole a tampinha na frente.", "Cole as janelinhas nas laterais.", "Gire a hélice e decole!"],
 brinca="Monte um aeroporto com fita crepe no chão e brinque de viajar para países imaginários.",
 apr="Equilíbrio e simetria (as duas asas iguais)."),
dict(n=13, t="Helicóptero de Hélice Giratória", c=1, i="5+", tm="40 min", d=2,
 mat=["1 caixa de leite", "2 palitos de picolé", "1 canudo", "2 grampos bailarina", "1 rolo de papel higiênico", "Tinta", "Cola quente (uso do adulto)"],
 pec=["Hélice principal: 2 palitos de picolé colados em X", "Hélice traseira: 1 palito cortado ao meio", "Cauda: tira de papelão de 15 x 3 cm", "Janela da frente: 6 x 5 cm", "Esquis: 2 canudos de 12 cm"],
 pas=["Pinte a caixa de leite e a cauda.", A+"Recorte a janela da frente na caixa.", "Cole a cauda na traseira, no alto.", A+"Prenda a hélice em X no teto com um grampo bailarina, para ela girar.", A+"Prenda a hélice traseira na ponta da cauda com o outro grampo.", "Cole os canudos embaixo da caixa como esquis.", "Desenhe o piloto na janela."],
 brinca="Brinque de resgate: o helicóptero busca bonecos 'presos' em cima dos móveis.",
 apr="Movimento de rotação e resolução de problemas."),
dict(n=14, t="Disco Voador Alienígena", c=1, i="3+", tm="25 min", d=1,
 mat=["2 pratos de papelão ou pratos descartáveis de papel", "1 copo plástico transparente", "Tampinhas coloridas", "Papel alumínio", "Massinha ou papel para o alien", "Cola"],
 pec=["Cúpula: 1 copo transparente", "Luzes: 6 a 8 tampinhas ou círculos de 2 cm coloridos", "Alienígena: bonequinho de massinha com 3 olhos"],
 pas=["Cubra os dois pratos com papel alumínio.", "Cole um prato virado sobre o outro, bordas com bordas.", "Cole as tampinhas coloridas em volta, como luzes.", "Modele o alienígena com massinha e coloque em cima.", "Cole o copo transparente por cima do alien, como cúpula."],
 brinca="Invente o nome e o planeta do alien e conte como foi a viagem até a Terra.",
 apr="Imaginação, narrativa e formas circulares."),
dict(n=15, t="Capacete de Astronauta", c=1, i="4+", tm="45 min", d=2,
 mat=["1 caixa de papelão onde caiba a cabeça da criança", "Papel alumínio ou tinta prata", "Papel celofane azul ou transparente", "Tampinhas coloridas", "Canudos", "Fita crepe"],
 pec=["Visor: retângulo de 18 x 12 cm com cantos arredondados, recortado na frente da caixa", "Antena: canudo com uma bolinha de papel na ponta", "Painel lateral: 4 tampinhas coloridas"],
 pas=[A+"Recorte a abertura de baixo para a cabeça e o visor na frente. Lixe ou cubra as bordas com fita crepe.", "Cubra a caixa com papel alumínio ou pinte de prata.", "Cole o celofane por dentro, tampando o visor.", "Cole as tampinhas numa lateral como botões de comunicação.", "Cole a antena no topo.", "Escreva o nome da criança e uma bandeira na testa."],
 brinca="Faça uma missão: o astronauta atravessa o 'espaço' (a sala) sem tocar no chão de lava.",
 apr="Faz de conta, autoestima e interesse por ciências."),
dict(n=16, t="Estação Espacial Modular", c=1, i="6+", tm="60 min", d=3,
 mat=["3 rolos de papel higiênico", "1 caixa de creme dental", "Papelão fino", "Papel alumínio", "Palitos de churrasco sem ponta", "Cola quente (uso do adulto)"],
 pec=["4 painéis solares de 12 x 5 cm (papelão coberto de alumínio, com quadriculado de canetinha)", "Janelas de 1,5 cm em todos os módulos"],
 pas=["Cubra rolos e caixa com papel alumínio.", A+"Cole os rolos nas pontas e nas laterais da caixa, formando uma cruz.", "Faça o quadriculado azul nos painéis solares.", A+"Espete os palitos nos módulos e cole os painéis neles.", "Desenhe as janelas e escreva o nome da estação.", "Pendure no teto com barbante, se quiser."],
 brinca="Os astronautas de brinquedo 'moram' na estação: invente a rotina deles no espaço.",
 apr="Montagem por módulos, planejamento e ciência."),
dict(n=17, t="Balão de Ar Quente", c=1, i="4+", tm="40 min", d=2,
 mat=["1 bexiga", "Jornal ou papel picado", "Cola branca misturada com água (papel machê)", "1 copinho de iogurte ou caixinha", "Barbante", "Tintas coloridas"],
 pec=["Cesto: copinho de iogurte ou caixinha de 5 x 5 cm", "4 fios de barbante de 12 cm"],
 pas=["Encha a bexiga e cubra com 3 camadas de jornal e cola.", "Espere secar por um dia.", "Pinte o balão com listras bem coloridas.", A+"Faça 4 furinhos no cesto.", "Amarre um barbante em cada furo e cole as outras pontas no balão.", "Coloque um bonequinho dentro do cesto e pendure."],
 brinca="Pendure o balão na janela e invente para onde ele está voando hoje.",
 apr="Paciência (esperar secar), texturas e cores."),
dict(n=18, t="Satélite Espião", c=1, i="5+", tm="35 min", d=2,
 mat=["1 caixa pequena (de remédio ou chá)", "Papelão fino", "Papel alumínio", "1 tampinha", "1 palito de churrasco sem ponta", "Cola"],
 pec=["2 painéis solares de 10 x 5 cm", "Antena parabólica: círculo de 6 cm com um corte até o centro, sobreposto para virar prato", "Haste: palito de 15 cm"],
 pas=["Cubra a caixinha com papel alumínio.", "Faça o quadriculado nos painéis e cole um de cada lado.", "Monte o prato da antena sobrepondo o corte e colando.", "Cole a antena na frente da caixa.", A+"Espete o palito embaixo para segurar o satélite.", "Pendure ou apoie num vaso."],
 brinca="Brinque de mandar mensagens secretas do satélite para a base na Terra.",
 apr="Comunicação e curiosidade sobre tecnologia."),
dict(n=19, t="Sistema Solar de Pendurar", c=1, i="5+", tm="60 min", d=2,
 mat=["1 pedaço grande de papelão ou prato de papelão", "Papelão fino", "Tintas", "Barbante", "Cola"],
 pec=["Sol: círculo de 12 cm", "Júpiter 9 cm · Saturno 8 cm (com anel de 14 cm) · Urano 6 cm · Netuno 6 cm", "Terra 4 cm · Vênus 4 cm · Marte 3 cm · Mercúrio 2 cm"],
 pas=["Recorte todos os círculos nos tamanhos indicados.", "Pinte cada planeta com a cor dele (Terra azul e verde, Marte vermelho, Júpiter com listras…).", "Escreva o nome de cada planeta atrás.", A+"Faça um furinho em cada um.", "Amarre barbantes de tamanhos diferentes.", "Prenda todos num prato ou tira de papelão, com o Sol no meio."],
 brinca="Peça para a criança colocar os planetas na ordem certa, do mais perto ao mais longe do Sol.",
 apr="Tamanhos, sequência e primeiras noções de astronomia."),
dict(n=20, t="Painel de Nave Espacial", c=1, i="4+", tm="45 min", d=2,
 mat=["1 caixa grande aberta (ou tampa de caixa grande)", "Tampinhas de várias cores", "Rolos de papel higiênico", "1 prato de papel", "Grampos bailarina", "Canetinhas"],
 pec=["Tela: retângulo de 15 x 10 cm de papel preto", "Volante: prato de papel", "Botões: 10 a 15 tampinhas", "Alavancas: 2 rolos cortados de 6 cm"],
 pas=["Deixe a caixa em pé como um painel.", "Cole a tela no centro e desenhe estrelas e planetas com canetinha.", A+"Prenda o prato com um grampo bailarina para ele girar como volante.", "Cole as tampinhas como botões e escreva números.", "Cole os rolos como alavancas.", "Desenhe medidores (combustível, velocidade)."],
 brinca="A criança é a comandante: aperte os botões na ordem da missão para fazer a nave decolar.",
 apr="Números, sequência e comando de voz."),
]
