A = "[ADULTO] "
P = [
# ---------------- FUNDO DO MAR (c=2) ----------------
dict(n=21, t="Barquinho a Vela que Flutua", c=2, i="3+", tm="25 min", d=1,
 mat=["1 caixa de leite vazia e lavada", "1 palito de churrasco sem ponta", "1 folha de papel colorido ou EVA", "Massinha", "Fita adesiva larga", "Canetinhas permanentes"],
 pec=["Casco: caixa de leite cortada ao meio no comprimento", "Vela: triângulo de 12 x 10 cm", "Bandeirinha: retângulo de 4 x 2 cm"],
 pas=[A+"Corte a caixa de leite ao meio no comprimento: cada metade vira um barco.", "Cubra o barco com fita adesiva larga para ele não molhar.", "Decore a vela e a bandeirinha com canetinha.", A+"Faça 2 furinhos na vela e passe o palito por eles.", "Prenda o palito no fundo do barco com uma bolinha de massinha.", "Coloque na bacia ou banheira e sopre a vela!"],
 brinca="Apostem corrida de barquinhos numa bacia com água, soprando com canudos.",
 apr="Flutuação, sopro (musculatura da fala) e experimentação."),
dict(n=22, t="Navio Pirata do Capitão", c=2, i="5+", tm="60 min", d=3,
 mat=["1 caixa de sapato", "2 palitos de churrasco sem ponta", "Papel branco e preto", "1 rolo de papel higiênico", "Barbante", "Tinta marrom", "Cola quente (uso do adulto)"],
 pec=["Proa: 2 triângulos de papelão de 12 x 8 cm (colados na frente)", "2 velas: retângulos de 12 x 10 cm", "Bandeira pirata: retângulo preto de 6 x 4 cm com caveira desenhada", "Canhões: rolo cortado em 3 pedaços de 3 cm"],
 pas=["Pinte a caixa de marrom e desenhe as tábuas de madeira com canetinha.", A+"Cole os triângulos na frente formando a proa pontuda.", A+"Faça 2 furos no fundo e firme os palitos (mastros) com cola quente.", "Faça 2 cortinhos em cada vela e passe pelo mastro, deixando-as curvadas como se tivesse vento.", "Cole a bandeira pirata no mastro mais alto.", "Cole os canhões nas laterais e faça uma escada de barbante."],
 brinca="Esconda um 'tesouro' pela casa e desenhe um mapa com X para a tripulação encontrar.",
 apr="Leitura de mapa, orientação espacial e trabalho em equipe."),
dict(n=23, t="Submarino Explorador", c=2, i="4+", tm="35 min", d=2,
 mat=["1 garrafa PET pequena ou rolo de papel toalha", "2 tampinhas", "1 canudo dobrável", "Papelão fino", "Tinta amarela", "Cola"],
 pec=["Torre: retângulo de 6 x 4 cm dobrado em caixinha", "Periscópio: canudo dobrável", "3 escotilhas: círculos de 3 cm", "Hélice: 1 tampinha com uma cruz de papelão"],
 pas=["Pinte o rolo ou a garrafa de amarelo.", "Cole a torre em cima, no meio.", "Encaixe o canudo na torre como periscópio.", "Cole as escotilhas nas laterais e desenhe peixes olhando pela janela.", "Cole a hélice na traseira."],
 brinca="Apague as luzes e explore o 'fundo do mar' com uma lanterna procurando bichinhos escondidos.",
 apr="Curiosidade, exploração e noção de em cima e embaixo."),
dict(n=24, t="Polvo de Oito Braços", c=2, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Tinta roxa ou rosa", "2 olhinhos móveis ou papel branco", "Canetinha", "Tesoura sem ponta"],
 pec=["8 braços: 8 cortes de 4 cm na parte de baixo do rolo", "2 olhos de 2 cm"],
 pas=["Pinte o rolo por dentro e por fora e deixe secar.", "Faça 8 cortes de 4 cm na parte de baixo do rolo.", "Enrole a ponta de cada braço num lápis para eles ficarem enroladinhos.", "Cole os olhos e desenhe um sorriso.", "Faça bolinhas com a ponta da canetinha nos braços, como ventosas."],
 brinca="Conte os braços do polvo juntos e brinque de 'o polvo pegou': cada braço segura um objeto.",
 apr="Contagem até 8, tesoura e coordenação motora fina."),
dict(n=25, t="Peixe-Palhaço Listrado", c=2, i="3+", tm="20 min", d=1,
 mat=["1 prato de papel ou papelão", "Tinta laranja, branca e preta", "Papel colorido", "Cola", "Canetinha"],
 pec=["Corpo: prato de papel com um triângulo de 8 cm recortado (a boca)", "Cauda: o próprio triângulo recortado, colado do lado oposto", "3 faixas de papel branco de 2 cm de largura"],
 pas=["Recorte o triângulo da boca no prato.", "Cole esse triângulo do outro lado: ele vira a cauda.", "Pinte o peixe de laranja.", "Cole as 3 faixas brancas e contorne com canetinha preta.", "Desenhe o olho e as nadadeiras."],
 brinca="Pendure o peixe num barbante e brinque de pescaria com um anzol de clipe.",
 apr="Reaproveitamento de formas, cores e padrões (listras)."),
dict(n=26, t="Tartaruga Marinha", c=2, i="3+", tm="30 min", d=1,
 mat=["1 prato de papel ou metade de uma caixa de ovos", "Papelão fino", "Tinta verde", "Canetinha", "Cola"],
 pec=["Casco: prato de papel ou 1 casinha da caixa de ovos", "Cabeça: círculo de 5 cm", "4 nadadeiras: gotas de 6 x 3 cm", "Cauda: triângulo de 2 cm"],
 pas=["Pinte o casco de verde e desenhe hexágonos (a 'colmeia' do casco).", "Pinte a cabeça, as nadadeiras e a cauda de verde-claro.", "Cole a cabeça na frente, as nadadeiras nos lados e a cauda atrás.", "Desenhe olhinhos e um sorriso."],
 brinca="Faça uma 'praia' com uma toalha e ajude a tartaruga a chegar até o mar (o tapete azul).",
 apr="Formas geométricas e cuidado com os animais."),
dict(n=27, t="Baleia Esguicho", c=2, i="3+", tm="30 min", d=1,
 mat=["1 caixa de leite ou de cereal", "Papel azul", "Papel celofane azul-claro", "Olhinhos", "Cola"],
 pec=["Cauda: formato de coração de 10 cm", "2 nadadeiras: gotas de 6 cm", "Esguicho: 3 tiras de celofane de 10 x 1,5 cm"],
 pas=["Cubra a caixa com papel azul, deitada.", "Cole a cauda em pé na traseira.", "Cole as nadadeiras nos lados.", "Cole as tiras de celofane no topo, saindo para cima como água.", "Cole os olhos e desenhe uma boca bem comprida."],
 brinca="Brinque de adivinhar: quantos peixinhos de papel cabem dentro da barriga da baleia?",
 apr="Tamanho (grande e pequeno) e contagem."),
dict(n=28, t="Farol que Ilumina", c=2, i="5+", tm="45 min", d=2,
 mat=["2 rolos de papel toalha ou 1 garrafa PET", "1 copo plástico transparente", "1 luzinha de LED ou lanterna pequena", "Tinta branca e vermelha", "1 tampa de pote", "Cola quente (uso do adulto)"],
 pec=["Base: tampa de pote de 10 cm", "Listras: faixas vermelhas de 3 cm", "Teto: cone de papel de 8 cm", "Janelinha: 3 x 2 cm"],
 pas=["Pinte o rolo de branco e depois faça listras vermelhas.", A+"Cole o rolo em pé na tampa de pote.", "Coloque a luzinha no topo do rolo.", A+"Cole o copo transparente virado por cima da luz.", "Cole o cone vermelho em cima do copo.", "Desenhe a porta e a janelinha."],
 brinca="Apague as luzes e guie os barquinhos de papel até o porto seguro.",
 apr="Luz e sombra, profissões do mar e segurança."),
dict(n=29, t="Caranguejo de Garras", c=2, i="4+", tm="30 min", d=2,
 mat=["1 prato de papel ou caixa de ovos", "Papelão fino", "2 grampos bailarina", "Tinta vermelha", "Olhinhos", "Cola"],
 pec=["Corpo: meio prato de papel ou 1 casinha da caixa de ovos", "2 garras: formato de 'C' de 6 cm", "6 perninhas: tiras de 5 x 1 cm dobradas em zigue-zague"],
 pas=["Pinte o corpo, as garras e as perninhas de vermelho.", A+"Prenda as garras no corpo com grampos bailarina: elas mexem!", "Dobre as perninhas em zigue-zague e cole 3 de cada lado.", "Cole os olhinhos em cima."],
 brinca="Faça o caranguejo andar de lado pela casa e 'beliscar' objetos com as garras.",
 apr="Lateralidade (andar de lado) e movimento."),
dict(n=30, t="Aquário na Caixa", c=2, i="5+", tm="60 min", d=2,
 mat=["1 caixa de sapato", "Papel celofane azul", "Papel colorido", "Barbante ou linha", "Pedrinhas ou papel amassado", "Tinta azul"],
 pec=["Janela: recorte a tampa deixando uma moldura de 2 cm", "5 peixes de 5 a 8 cm", "3 algas: tiras onduladas de 12 x 2 cm", "Estrela-do-mar de 4 cm"],
 pas=["Pinte o fundo da caixa por dentro de azul.", "Cole algas e estrela-do-mar no fundo, e pedrinhas no chão.", "Pinte os peixes dos dois lados.", A+"Pendure os peixes com linha no 'teto' da caixa, em alturas diferentes.", A+"Recorte a janela na tampa e cole o celofane.", "Tampe e olhe pela janela: o aquário está pronto!"],
 brinca="Dê nome para cada peixe e invente a história da família que mora no aquário.",
 apr="Composição, profundidade e narrativa."),
# ---------------- CASAS E CIDADE (c=3) ----------------
dict(n=31, t="Casinha da Caixa de Leite", c=3, i="3+", tm="30 min", d=1,
 mat=["1 caixa de leite vazia e lavada", "Papel colorido", "Canetinhas", "Tinta ou papel para cobrir", "Cola"],
 pec=["Telhado: retângulo de 10 x 12 cm dobrado ao meio", "Porta: 3 x 5 cm", "2 janelas: 3 x 3 cm", "Chaminé: 2 x 3 cm"],
 pas=["Feche a caixa em forma de 'telhado' com fita crepe.", "Pinte ou cubra as paredes.", "Dobre o telhado ao meio e cole por cima.", "Cole a porta, as janelas e a chaminé.", "Desenhe cortinas, flores e o número da casa."],
 brinca="Faça várias casinhas e monte uma rua com o nome da família na plaquinha.",
 apr="Moradia, endereço e formas geométricas."),
dict(n=32, t="Prédio de Apartamentos", c=3, i="4+", tm="40 min", d=1,
 mat=["2 ou 3 caixas de cereal ou creme dental", "Papel colorido ou tinta", "Canetinhas", "Fita crepe", "Cola"],
 pec=["Janelas: 12 a 20 quadrados de 2,5 cm", "Porta de entrada: 4 x 6 cm", "Placa com o nome do prédio: 8 x 2 cm"],
 pas=["Empilhe as caixas em pé e prenda com fita crepe.", "Pinte a fachada.", "Cole as janelas em fileiras, andar por andar.", "Em algumas janelas, desenhe moradores, gatinhos ou vasos.", "Cole a porta e a placa.", "Numere os andares."],
 brinca="Brinque de elevador: 'Seu João mora no 3º andar!' A criança sobe o bonequinho até o andar certo.",
 apr="Números ordinais (1º, 2º, 3º) e contagem."),
dict(n=33, t="Mercadinho da Esquina", c=3, i="4+", tm="45 min", d=2,
 mat=["1 caixa grande aberta ou caixa de sapato", "Embalagens pequenas vazias (iogurte, remédio, chá)", "Papel colorido", "Canetinhas", "Cola"],
 pec=["Toldo: retângulo de 25 x 8 cm com listras e borda em ondas", "Placa: 15 x 4 cm com o nome do mercado", "Prateleiras: tiras de papelão de 20 x 5 cm", "Etiquetas de preço: 12 retângulos de 3 x 2 cm"],
 pas=["Deixe a caixa em pé, aberta na frente.", "Cole as tiras de papelão por dentro como prateleiras.", "Cole o toldo listrado e a placa em cima.", "Arrume as embalagens vazias nas prateleiras.", "Escreva os preços nas etiquetas e cole na frente de cada produto."],
 brinca="Brinque de fazer compras com uma lista desenhada e dinheirinho de papel.",
 apr="Números, dinheiro, lista de compras e troca de turnos."),
dict(n=34, t="Posto de Gasolina", c=3, i="4+", tm="45 min", d=2,
 mat=["1 caixa de sapato", "2 caixinhas de creme dental", "Barbante ou fio de fone velho", "Tampinhas", "Tintas", "Cola quente (uso do adulto)"],
 pec=["Cobertura: tampa da caixa apoiada em 4 rolos de 8 cm", "2 bombas: caixinhas de creme dental em pé", "Mangueiras: barbante de 15 cm com tampinha na ponta", "Visor de preço: 3 x 2 cm"],
 pas=["Pinte a caixa de sapato como a lojinha do posto.", "Pinte as caixinhas como bombas de combustível.", "Cole o visor de números em cada bomba.", A+"Cole o barbante com a tampinha na lateral de cada bomba.", "Monte a cobertura com a tampa e os rolos.", "Desenhe as faixas de entrada e saída no chão."],
 brinca="Os carrinhos param no posto, pedem 'completa, por favor' e pagam com moedinhas de papel.",
 apr="Rotina da cidade, números e conversa (pedir e agradecer)."),
dict(n=35, t="Garagem com Rampa", c=3, i="4+", tm="50 min", d=2,
 mat=["2 caixas de sapato", "1 tira comprida de papelão", "Rolos de papel higiênico", "Fita crepe", "Canetinhas", "Cola quente (uso do adulto)"],
 pec=["Rampa: tira de papelão de 40 x 8 cm", "Portão: retângulo de 10 x 7 cm (abre com fita crepe)", "Vagas: linhas de 6 cm desenhadas no chão"],
 pas=["Coloque uma caixa em cima da outra: são 2 andares.", A+"Recorte o portão no andar de baixo e prenda com fita para abrir e fechar.", A+"Cole a rampa descendo do andar de cima até o chão.", "Use rolos como apoio embaixo da rampa, se precisar.", "Desenhe as vagas e numere de 1 a 10."],
 brinca="Solte os carrinhos da rampa e veja qual vai mais longe. Depois estacione cada um na vaga do número sorteado.",
 apr="Velocidade, números e noção de inclinação."),
dict(n=36, t="Hospital dos Bichinhos", c=3, i="4+", tm="45 min", d=2,
 mat=["1 caixa de sapato grande", "Caixinhas de remédio vazias (limpas)", "Gaze ou retalho de pano", "Papel branco e vermelho", "Canetinhas", "Cola"],
 pec=["Cruz vermelha: 2 retângulos de 8 x 2,5 cm", "Camas: caixinhas de remédio com lençol de pano", "Placa: HOSPITAL em 12 x 3 cm"],
 pas=["Deixe a caixa aberta, em pé, como um prédio visto por dentro.", "Cole a cruz vermelha e a placa em cima.", "Monte as caminhas com as caixinhas e cubra com pano.", "Desenhe um relógio e um armário de remédios na parede.", "Faça plaquinhas com o nome de cada paciente."],
 brinca="Os bichinhos de pelúcia chegam 'dodóis' e a criança é a médica que cuida de cada um.",
 apr="Empatia, cuidado e vocabulário do corpo humano."),
dict(n=37, t="Escolinha com Quadro", c=3, i="4+", tm="45 min", d=1,
 mat=["1 caixa de sapato", "Papel preto ou verde-escuro", "Tampinhas", "Palitos de picolé", "Giz ou canetinha branca", "Cola"],
 pec=["Quadro: retângulo de 12 x 7 cm de papel preto", "Carteiras: 6 palitos de picolé com tampinhas como cadeiras", "Sino: triângulo de 3 cm"],
 pas=["Deixe a caixa aberta como uma sala de aula.", "Cole o quadro na parede do fundo.", "Monte as carteiras colando os palitos em cima de tampinhas.", "Escreva letras ou números no quadro.", "Cole o sino no alto, do lado de fora."],
 brinca="A criança é a professora: ensina as letras do nome para os bonecos alunos.",
 apr="Letras, números e rotina escolar."),
dict(n=38, t="Padaria do Bairro", c=3, i="4+", tm="45 min", d=2,
 mat=["1 caixa de sapato", "Massinha ou papel amassado para os pães", "Papel colorido", "1 tampa de pote para bandeja", "Canetinhas", "Cola"],
 pec=["Balcão: faixa de papelão de 20 x 6 cm", "Toldo: 20 x 5 cm com listras", "Placa: PADARIA 12 x 3 cm", "Pães: bolinhas e rolinhos de massinha"],
 pas=["Deixe a caixa em pé, aberta na frente.", "Cole o balcão na frente, embaixo.", "Cole o toldo e a placa em cima.", "Modele pães, bolos e sonhos com massinha.", "Arrume os pães na bandeja e escreva os preços."],
 brinca="Brinque de padeiro: anote os pedidos e 'entregue' o pão quentinho de manhã.",
 apr="Modelagem, quantidades e interação social."),
dict(n=39, t="Ponte Levadiça da Cidade", c=3, i="5+", tm="40 min", d=2,
 mat=["1 tira comprida de papelão", "4 rolos de papel higiênico", "Barbante", "Papel azul", "Canetinhas", "Cola quente (uso do adulto)"],
 pec=["Pista: tira de papelão de 40 x 8 cm", "Rio: faixa de papel azul de 50 x 15 cm", "Faixas da pista: tracinhos de 2 cm"],
 pas=["Estique o papel azul no chão: é o rio.", A+"Cole 2 rolos de cada lado do rio, como pilares.", A+"Cole a pista em cima dos rolos.", "Desenhe a faixa amarela no meio da pista.", "Amarre barbante dos rolos até a pista, como cabos de uma ponte de verdade."],
 brinca="Os carrinhos atravessam a ponte e os barquinhos de papel passam por baixo.",
 apr="Noções de engenharia, em cima e embaixo, equilíbrio."),
dict(n=40, t="Semáforo que Acende", c=3, i="3+", tm="30 min", d=1,
 mat=["1 caixa de creme dental ou de remédio comprida", "Papel preto", "Papel celofane vermelho, amarelo e verde (ou papel colorido)", "1 rolo de papel toalha", "Cola"],
 pec=["3 luzes: círculos de 3,5 cm (vermelho, amarelo, verde)", "3 viseiras: meias-luas de 4 cm", "Poste: rolo de papel toalha"],
 pas=["Cubra a caixa com papel preto.", "Cole as luzes na ordem: vermelho em cima, amarelo no meio, verde embaixo.", "Cole uma viseira em cima de cada luz.", "Cole a caixa em cima do rolo."],
 brinca="A criança controla o trânsito: vermelho todo mundo para, verde todo mundo anda!",
 apr="Regras de trânsito, cores e controle do impulso (parar e seguir)."),
]
