A = "[ADULTO] "
P = [
# ---------------- CASTELOS E FANTASIA (c=4) ----------------
dict(n=41, t="Castelo de Quatro Torres", c=4, i="4+", tm="60 min", d=2,
 mat=["1 caixa de sapato", "4 rolos de papel higiênico", "Papel colorido", "Palitos de dente", "Tinta cinza ou lilás", "Cola quente (uso do adulto)"],
 pec=["Muralha: ameias de 2 x 2 cm recortadas na borda da caixa (um quadrado sim, um não)", "4 telhados: cones feitos com meio círculo de 10 cm", "Portão: arco de 6 x 8 cm", "4 bandeirinhas: triângulos de 3 cm"],
 pas=[A+"Recorte as ameias na borda de cima da caixa.", A+"Recorte o portão em arco na frente, deixando dobrado para baixo como uma ponte.", "Pinte a caixa e os rolos.", A+"Cole um rolo em cada canto da caixa.", "Enrole os cones e cole em cima dos rolos.", "Cole as bandeirinhas nos palitos e espete no topo dos cones.", "Desenhe pedras e janelinhas."],
 brinca="Invente um reino: quem é o rei, quem guarda o portão e qual é a senha secreta para entrar.",
 apr="Narrativa, faz de conta e simetria."),
dict(n=42, t="Torre da Princesa", c=4, i="4+", tm="40 min", d=2,
 mat=["1 rolo de papel toalha", "1 folha de papel colorido", "Lã amarela ou marrom", "Papelão fino", "Canetinhas", "Cola"],
 pec=["Telhado: cone com meio círculo de 14 cm", "Janela: arco de 4 x 5 cm", "Trança: 10 fios de lã de 30 cm trançados", "Heras: folhinhas de papel verde de 2 cm"],
 pas=["Pinte ou cubra o rolo.", "Monte o cone do telhado e cole em cima.", "Desenhe a janela no alto e cole a trança de lã saindo dela.", "Cole as folhinhas subindo pela torre.", "Desenhe tijolos com canetinha."],
 brinca="Conte uma história em que a princesa usa a própria trança para salvar alguém lá embaixo.",
 apr="Trançar (coordenação fina) e inversão de histórias clássicas."),
dict(n=43, t="Espada e Escudo do Cavaleiro", c=4, i="4+", tm="45 min", d=2,
 mat=["1 caixa de papelão grande", "Papel alumínio", "Fita crepe", "Tintas", "Canetinhas"],
 pec=["Escudo: formato de brasão de 30 x 35 cm", "Alça do escudo: tira de 25 x 4 cm", "Espada: lâmina de 45 x 6 cm com ponta arredondada", "Guarda da espada: retângulo de 15 x 4 cm"],
 pas=[A+"Recorte o escudo e as peças da espada em papelão grosso.", "Cubra a lâmina com papel alumínio.", "Cole a guarda atravessada na espada e enrole fita crepe no cabo.", "Pinte o escudo e crie um brasão da família (um animal, uma cor, uma inicial).", A+"Prenda a alça atrás do escudo com fita crepe bem firme."],
 brinca="Faça uma cerimônia: a criança é nomeada 'Cavaleiro(a) Protetor(a) da Casa'.",
 apr="Identidade, coragem e criatividade (criar o próprio brasão)."),
dict(n=44, t="Coroa Real Brilhante", c=4, i="3+", tm="25 min", d=1,
 mat=["1 caixa de cereal", "Papel dourado ou tinta amarela", "Tampinhas, botões ou papel brilhante", "Grampeador (uso do adulto)", "Cola"],
 pec=["Faixa da coroa: 55 x 10 cm (meça a cabeça da criança + 3 cm)", "5 pontas: triângulos de 6 cm na borda de cima", "Joias: círculos de 2 cm coloridos"],
 pas=["Abra a caixa de cereal e desenhe a faixa com as pontas.", A+"Recorte a coroa.", "Pinte de dourado ou cubra com papel brilhante.", "Cole as 'joias' em cada ponta.", A+"Feche a coroa no tamanho da cabeça com grampeador ou fita."],
 brinca="Coroação! Faça um tapete vermelho com uma toalha e anuncie o novo rei ou rainha.",
 apr="Autoestima, padrões e medidas (o tamanho da cabeça)."),
dict(n=45, t="Dragão Amigo", c=4, i="5+", tm="45 min", d=2,
 mat=["1 rolo de papel toalha", "1 rolo de papel higiênico", "Papel celofane laranja e vermelho", "Papelão fino", "Tinta verde", "Cola quente (uso do adulto)"],
 pec=["2 asas: formato de leque de 15 x 10 cm", "Espinhos: 6 triângulos de 3 cm", "Fogo: 4 tiras de celofane de 12 x 2 cm", "Rabo: triângulo comprido de 15 x 5 cm"],
 pas=["Pinte os dois rolos de verde.", A+"Cole o rolo pequeno inclinado na frente do grande: ele é o pescoço e a cabeça.", "Cole as asas nas costas e os espinhos em fila.", "Cole o rabo atrás.", "Cole as tiras de celofane saindo da boca.", "Desenhe olhos e narinas."],
 brinca="Assopre no rolo da cabeça e veja o 'fogo' de celofane balançar!",
 apr="Sopro, imaginação e superação de medos com personagens amigos."),
dict(n=46, t="Carruagem Encantada", c=4, i="5+", tm="50 min", d=2,
 mat=["1 caixa de sapato pequena ou caixa de leite", "4 tampas de pote", "2 palitos de churrasco sem ponta", "Papel dourado", "Tinta rosa ou azul", "Cola quente (uso do adulto)"],
 pec=["Janelas: 2 arcos de 5 x 6 cm", "Teto: meia-lua de 12 cm com uma bolinha em cima", "4 rodas de 7 cm com raios desenhados", "Porta: arco de 5 x 7 cm"],
 pas=[A+"Recorte as janelas em arco nas laterais.", "Pinte a carruagem e contorne tudo de dourado.", A+"Passe os palitos pela base e cole as rodas nas pontas.", "Cole o teto curvado em cima.", "Desenhe os raios nas rodas com canetinha."],
 brinca="A carruagem leva os convidados ao baile: vale música e dança no final!",
 apr="Faz de conta, formas curvas e coordenação."),
dict(n=47, t="Casa na Árvore", c=4, i="5+", tm="60 min", d=3,
 mat=["1 rolo de papel toalha (tronco)", "1 caixa pequena (a casinha)", "Papel verde amassado", "Palitos de picolé", "Barbante", "Cola quente (uso do adulto)"],
 pec=["Copa da árvore: bolas de papel verde amassado", "Escada: 2 barbantes de 25 cm com palitos de 5 cm", "Janela e porta: 2 x 2 cm e 3 x 4 cm", "Plataforma: tampa de caixa ou papelão de 12 x 12 cm"],
 pas=["Pinte o rolo de marrom e desenhe a casca.", A+"Cole a plataforma no alto do tronco.", A+"Cole a caixa em cima da plataforma e recorte janela e porta.", "Cole as bolas verdes em volta: é a copa.", "Monte a escada de barbante e palitos e pendure da porta até o chão."],
 brinca="Crie o 'clube secreto' da casa na árvore com senha, regras e um mapa.",
 apr="Construção em camadas e combinados em grupo."),
dict(n=48, t="Baú do Tesouro", c=4, i="4+", tm="40 min", d=2,
 mat=["1 caixa de sapato com tampa", "Tinta marrom e dourada", "Papel alumínio", "Botões e tampinhas", "Fita crepe"],
 pec=["Tampa curva: tira de papelão de 30 x 12 cm dobrada em arco", "Fechadura: círculo de 4 cm com um buraco desenhado", "Faixas de metal: 2 tiras de 2 cm de largura"],
 pas=["Pinte a caixa de marrom e desenhe as tábuas.", "Cole a tira em arco em cima da tampa para ficar curva.", "Prenda a tampa na caixa com fita crepe de um lado, como dobradiça.", "Cole as faixas douradas e a fechadura.", "Encha de 'tesouros': botões, moedas de papel e pedrinhas."],
 brinca="Esconda o baú e faça uma caça ao tesouro com pistas desenhadas.",
 apr="Raciocínio, seguir pistas e guardar os próprios objetos."),
dict(n=49, t="Trono do Rei e da Rainha", c=4, i="5+", tm="60 min", d=3,
 mat=["1 caixa de papelão grande e firme (onde a criança consiga sentar)", "Almofada", "Papel dourado ou tinta amarela", "Tinta vermelha ou roxa", "Fita crepe larga"],
 pec=["Encosto: retângulo alto de 50 x 70 cm com pontas de coroa em cima", "Braços: 2 retângulos de 30 x 15 cm", "Joias: círculos coloridos de 4 cm"],
 pas=["Reforce a caixa com fita crepe e coloque jornal amassado dentro para aguentar peso.", A+"Recorte o encosto com pontas de coroa e cole atrás da caixa.", A+"Cole os braços nas laterais.", "Pinte de vermelho e contorne de dourado.", "Cole as joias e coloque a almofada no assento."],
 brinca="Hora da audiência real: a família faz 'pedidos' e o rei ou a rainha decide.",
 apr="Autoconfiança, tomada de decisão e expressão oral."),
dict(n=50, t="Porta do Castelo que Sobe e Desce", c=4, i="6+", tm="45 min", d=3,
 mat=["1 caixa de sapato", "1 rolo de papel higiênico", "Barbante", "1 palito de churrasco sem ponta", "Tinta", "Cola quente (uso do adulto)"],
 pec=["Ponte: retângulo de 10 x 14 cm (a própria parte recortada da caixa)", "Rolo de manivela: pedaço de 6 cm de rolo", "Correntes: 2 barbantes de 25 cm"],
 pas=[A+"Recorte 3 lados de um retângulo na frente da caixa, deixando o lado de baixo preso: vira a ponte.", A+"Faça 2 furinhos no topo da ponte e amarre um barbante em cada.", A+"Atravesse o palito na parte de cima da caixa passando pelo rolo.", "Prenda as pontas dos barbantes no rolo.", "Gire o palito: a ponte sobe e desce!", "Pinte as pedras do castelo."],
 brinca="Só entra no castelo quem acertar a charada do guarda!",
 apr="Mecânica simples (manivela), causa e efeito."),
# ---------------- ANIMAIS DA FAZENDA (c=5) ----------------
dict(n=51, t="Vaquinha Malhada", c=5, i="3+", tm="30 min", d=1,
 mat=["1 caixa de leite vazia e lavada", "Papel branco", "Papel preto e rosa", "4 rolinhos ou tampinhas para as patas", "Canetinha", "Cola"],
 pec=["Manchas pretas: 5 formatos irregulares de 3 a 5 cm", "Focinho: oval rosa de 5 x 3 cm", "2 orelhas: gotas de 3 cm", "2 chifres: triângulos de 1,5 cm", "Rabo: tira de 10 x 1 cm"],
 pas=["Cubra a caixa de leite com papel branco.", "Cole as manchas pretas.", "Cole o focinho, as orelhas e os chifres na frente.", "Cole as patas embaixo.", "Cole o rabo atrás e desenhe os olhos e as narinas."],
 brinca="Brinque de fazendeira: a vaquinha 'dá leite' (tampinhas brancas) que vai para o mercado.",
 apr="Animais da fazenda, origem do leite e sons dos bichos."),
dict(n=52, t="Porquinho Cofrinho", c=5, i="3+", tm="30 min", d=1,
 mat=["1 garrafa PET pequena ou pote redondo com tampa", "4 tampinhas", "Tinta rosa", "Limpador de cachimbo ou tira de papel", "Cola quente (uso do adulto)"],
 pec=["2 orelhas: triângulos de 4 cm", "Focinho: a própria tampa da garrafa pintada", "Rabo: espiral de papel ou limpador de cachimbo", "Fenda para moedas: 3 x 0,5 cm"],
 pas=["Pinte a garrafa de rosa.", A+"Recorte a fenda para as moedas em cima.", A+"Cole as 4 tampinhas embaixo como patas.", "Pinte a tampa e desenhe as narinas: é o focinho.", "Cole as orelhas e o rabinho enrolado.", "Desenhe os olhos."],
 brinca="Comece a guardar moedas para um objetivo: 'o que vamos comprar quando ele encher?'",
 apr="Educação financeira, paciência e contagem de moedas."),
dict(n=53, t="Galinha com Ninho de Ovos", c=5, i="3+", tm="30 min", d=1,
 mat=["1 prato de papel ou papelão", "1 caixa de ovos", "Papel vermelho e amarelo", "Algodão ou papel picado", "Bolinhas de papel branco", "Cola"],
 pec=["Corpo: prato de papel dobrado ao meio", "Crista: 3 gotas vermelhas de 2 cm", "Bico: triângulo amarelo de 2 cm", "Ninho: 2 casinhas da caixa de ovos com papel picado"],
 pas=["Dobre o prato ao meio: ele vira o corpo da galinha em pé.", "Cole a crista, o bico e desenhe o olho.", "Pinte ou cole penas de papel nas laterais.", "Monte o ninho com a caixa de ovos e papel picado.", "Faça 'ovos' com bolinhas de papel branco e coloque no ninho."],
 brinca="Esconda os ovinhos pela casa: a criança encontra e devolve para a galinha contando um a um.",
 apr="Contagem, animais e ciclo de vida."),
dict(n=54, t="Cavalinho de Pau", c=5, i="4+", tm="45 min", d=2,
 mat=["1 caixa de cereal", "1 cabo de vassoura velho ou rolo comprido de papelão", "Lã para a crina", "Barbante (rédea)", "Tinta marrom", "Fita crepe"],
 pec=["Cabeça: perfil de cavalo de 25 x 20 cm (desenhado na caixa aberta, 2 lados iguais)", "2 orelhas: triângulos de 4 cm", "Crina: 15 fios de lã de 12 cm"],
 pas=["Desenhe o perfil da cabeça na caixa aberta.", A+"Recorte os dois lados iguais.", "Pinte, desenhe olho e narina dos dois lados.", "Cole a crina de lã entre as duas partes, no pescoço.", A+"Una as partes com cola, encaixando o cabo no pescoço, e prenda com fita crepe.", "Amarre o barbante como rédea."],
 brinca="Corrida de cavalinhos no quintal com obstáculos de almofada para pular.",
 apr="Movimento amplo, equilíbrio e imaginação."),
dict(n=55, t="Ovelhinha Fofinha", c=5, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Algodão", "Papel preto", "Cola branca", "Olhinhos"],
 pec=["Cabeça: oval preta de 4 x 5 cm", "2 orelhas: gotas pretas de 2,5 cm", "4 patas: tiras pretas de 4 x 1 cm"],
 pas=["Passe cola no rolo inteiro.", "Cubra o rolo com bolinhas de algodão: é a lã da ovelha.", "Cole as orelhas na cabeça e os olhinhos.", "Cole a cabeça na frente do rolo.", "Cole as 4 patas embaixo."],
 brinca="Conte ovelhinhas na hora de dormir. Faça várias e brinque de pastora levando todas para o cercado.",
 apr="Textura (tato), contagem e rotina do sono."),
dict(n=56, t="Celeiro Vermelho", c=5, i="4+", tm="50 min", d=2,
 mat=["1 caixa de sapato", "Papelão fino", "Tinta vermelha e branca", "Palha, barbante ou papel amarelo picado", "Cola quente (uso do adulto)"],
 pec=["Telhado: 2 retângulos de 22 x 10 cm", "2 frentes do telhado: triângulos de 16 x 8 cm", "Portão duplo: 2 retângulos de 5 x 8 cm com X branco", "Janelinha do sótão: 3 x 3 cm"],
 pas=["Deixe a caixa em pé e pinte de vermelho.", A+"Cole os triângulos nas pontas e os retângulos por cima, formando o telhado.", A+"Recorte o portão para abrir dos dois lados.", "Pinte o X branco nos portões e as bordas brancas.", "Coloque palha picada dentro."],
 brinca="Junte os bichos da fazenda: de noite todo mundo entra no celeiro, de dia sai para passear.",
 apr="Organização (guardar), dia e noite."),
dict(n=57, t="Patinho na Lagoa", c=5, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Tinta amarela", "Papel laranja", "1 prato de papel azul (a lagoa)", "Cola"],
 pec=["Bico: losango laranja de 3 cm dobrado ao meio", "2 asas: gotas de 5 cm", "2 pés: formato de pé de pato de 3 cm"],
 pas=["Pinte o rolo de amarelo.", "Cole o bico dobrado na frente, no alto.", "Cole as asas nos lados.", "Cole os pés embaixo.", "Pinte o prato de azul e coloque o pato em cima, na lagoa."],
 brinca="Faça vários patinhos em fila e cante enquanto eles 'vão passear'.",
 apr="Musicalidade, fila e sequência."),
dict(n=58, t="Coelho Saltitante", c=5, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Papel branco e rosa", "Algodão", "Canetinha", "Cola"],
 pec=["2 orelhas: 12 x 4 cm (formato de gota comprida) com o centro rosa", "Rabinho: bolinha de algodão", "Dentinhos: retângulo de 1,5 x 1 cm"],
 pas=["Cubra ou pinte o rolo de branco.", "Cole as orelhas em cima, por dentro do rolo.", "Desenhe olhos, focinho rosa e bigodes.", "Cole os dentinhos.", "Cole o rabinho de algodão atrás."],
 brinca="Pule como coelho de uma almofada até a outra levando 'cenourinhas' de papel.",
 apr="Movimento (pular), cores e animais."),
dict(n=59, t="Cachorro na Casinha", c=5, i="4+", tm="45 min", d=2,
 mat=["1 caixa de sapato pequena", "1 rolo de papel higiênico", "Papel marrom e preto", "Tinta", "Cola"],
 pec=["Telhado: 2 retângulos de 12 x 8 cm", "Porta em arco: 6 x 7 cm", "Cachorro: rolo com 2 orelhas caídas de 5 cm e um focinho de 3 cm", "Plaquinha com o nome: 6 x 2 cm", "Osso: formato de 5 cm"],
 pas=[A+"Recorte a porta em arco na frente da caixa.", A+"Monte o telhado inclinado com os 2 retângulos.", "Pinte a casinha.", "Monte o cachorrinho no rolo: pinte, cole orelhas e focinho, desenhe os olhos.", "Escreva o nome do cachorro na plaquinha e cole em cima da porta."],
 brinca="Treine o cachorrinho: 'senta', 'deita', 'busca o osso'!",
 apr="Cuidado com os animais e comandos (escuta)."),
dict(n=60, t="Gatinho Curioso", c=5, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Tinta laranja, cinza ou preta", "Papel", "Limpador de cachimbo ou tira de papel", "Canetinha"],
 pec=["Orelhas: dobre a borda de cima do rolo para dentro, dos dois lados, formando 2 pontas", "Rabo: tira de 12 x 1,5 cm ou limpador de cachimbo", "Bigodes: 6 tirinhas finas"],
 pas=["Dobre a parte de cima do rolo para dentro dos dois lados: aparecem as orelhinhas.", "Pinte o gato da cor que quiser.", "Desenhe olhos, focinho e listras.", "Cole os bigodes.", "Cole o rabo atrás, enrolado para cima."],
 brinca="Esconda o gatinho em algum lugar da casa e dê pistas: 'está quente' ou 'está frio'.",
 apr="Dobradura simples e percepção espacial."),
]
