A = "[ADULTO] "
P = [
# ---------------- ANIMAIS SELVAGENS (c=6) ----------------
dict(n=61, t="Leão Rei da Selva", c=6, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Papel laranja e marrom (ou lã)", "Tinta amarela", "Canetinha", "Cola"],
 pec=["Juba: círculo de 10 cm com franjas de 2 cm cortadas em volta", "Rosto: círculo amarelo de 5 cm", "2 orelhas: meias-luas de 2 cm", "Rabo: tira de 10 x 1 cm com um tufo na ponta"],
 pas=["Pinte o rolo de amarelo.", "Recorte a juba e faça os cortes em franja na borda.", "Cole o rosto no meio da juba e as orelhas em cima.", "Desenhe olhos, focinho e bigodes.", "Cole a cabeça na frente do rolo e o rabo atrás."],
 brinca="Quem ruge mais alto? Brinque de imitar os bichos da selva e adivinhar qual é.",
 apr="Recorte em franja, expressão e sons dos animais."),
dict(n=62, t="Girafa Pescoçuda", c=6, i="4+", tm="35 min", d=2,
 mat=["1 rolo de papel toalha", "1 rolo de papel higiênico", "Tinta amarela e marrom", "Papelão fino", "Cola quente (uso do adulto)"],
 pec=["Pescoço e cabeça: tira de papelão de 20 x 4 cm com a cabeça de 6 cm na ponta", "2 chifrinhos: palitos de 2 cm com bolinha", "4 pernas: cortes em formato de 'U' na base do rolo grande"],
 pas=[A+"Recorte 2 'U' na base do rolo grande, na frente e atrás: aparecem as 4 pernas.", "Pinte tudo de amarelo e faça manchas marrons.", A+"Cole o pescoço em pé na frente do corpo.", "Cole os chifrinhos e desenhe o rosto.", "Faça um rabo com um fio de lã."],
 brinca="Meça quem é mais alto: a girafa, o ursinho ou o carrinho? Compare tudo pela casa.",
 apr="Comparação de tamanhos (alto e baixo) e padrões (manchas)."),
dict(n=63, t="Elefante de Tromba Longa", c=6, i="3+", tm="30 min", d=1,
 mat=["1 garrafa PET pequena ou pote de iogurte", "Papel cinza", "Papelão fino", "Olhinhos", "Cola"],
 pec=["2 orelhas grandes: formato de leque de 10 cm", "Tromba: tira sanfonada de 15 x 3 cm", "2 presas: meias-luas brancas de 3 cm"],
 pas=["Pinte ou cubra o pote de cinza (a boca do pote vira o rosto).", "Cole as orelhas grandes dos lados.", "Faça a tromba dobrando o papel em sanfona.", "Cole a tromba no meio do rosto e as presas dos lados.", "Cole os olhinhos."],
 brinca="Estique e encolha a tromba: o elefante 'pega' bolinhas de papel e leva até a cesta.",
 apr="Dobradura em sanfona e coordenação."),
dict(n=64, t="Macaco Pendurado", c=6, i="4+", tm="30 min", d=1,
 mat=["1 rolo de papel higiênico", "Tinta marrom", "Papel bege", "Limpadores de cachimbo ou tiras de papel", "Cola"],
 pec=["Rosto: formato de coração bege de 5 cm", "2 orelhas: círculos de 2,5 cm", "Braços e rabo: 3 tiras de 18 x 1,5 cm"],
 pas=["Pinte o rolo de marrom.", "Cole o rosto bege e desenhe os olhos e um sorrisão.", "Cole as orelhas dos lados.", "Cole os braços compridos e o rabo.", "Enrole a ponta dos braços para o macaco se pendurar."],
 brinca="Pendure o macaquinho em cabides, maçanetas e galhos: onde ele consegue ficar?",
 apr="Resolução de problemas e equilíbrio."),
dict(n=65, t="Zebra Listrada", c=6, i="4+", tm="30 min", d=1,
 mat=["1 caixa de creme dental ou rolo de papel", "Papel branco", "Canetinha preta grossa ou fita isolante", "Lã preta", "Cola"],
 pec=["Cabeça: formato de 8 x 5 cm", "4 patas: rolinhos de papel de 5 cm", "Crina: fios de lã de 3 cm", "Listras: faixas pretas de 1 cm"],
 pas=["Cubra a caixa de branco.", "Faça listras pretas com canetinha ou tiras de fita isolante.", "Monte as patas enrolando papel e cole embaixo.", "Cole a cabeça listrada na frente.", "Cole a crina de lã."],
 brinca="Faça um jogo de padrões: branco, preto, branco… a criança continua a sequência.",
 apr="Padrões e sequência (base da matemática)."),
dict(n=66, t="Tigre Listrado", c=6, i="4+", tm="30 min", d=1,
 mat=["1 prato de papel", "Tinta laranja", "Canetinha preta", "Papel branco e rosa", "Cola"],
 pec=["Rosto: prato de papel", "2 orelhas: triângulos de 4 cm", "Focinho: 2 círculos brancos de 3 cm e nariz rosa de 1,5 cm"],
 pas=["Pinte o prato de laranja.", "Faça as listras pretas começando pelas bordas.", "Cole as orelhas em cima.", "Cole o focinho e o nariz.", A+"Recorte os buracos dos olhos para virar máscara (opcional) e prenda um elástico."],
 brinca="Coloque a máscara e brinque de tigre: andar de quatro, rugir e caçar almofadas.",
 apr="Expressão corporal e faz de conta."),
dict(n=67, t="Jacaré que Abre a Boca", c=6, i="5+", tm="40 min", d=2,
 mat=["2 caixas de ovos (a parte de 6)", "Tinta verde", "Papel branco", "Grampos bailarina ou fita crepe", "Olhinhos"],
 pec=["Mandíbulas: 2 metades da caixa de ovos", "Dentes: tira de papel branco em zigue-zague de 15 cm", "Olhos: 2 casinhas da caixa de ovos"],
 pas=["Pinte as caixas de verde por dentro e por fora.", "Encaixe uma metade sobre a outra, como boca, e prenda atrás com fita ou grampo.", "Cole os dentes em zigue-zague nas duas mandíbulas.", "Cole as casinhas como olhos em cima, com olhinhos.", "Pinte o céu da boca de rosa."],
 brinca="O jacaré está com fome: alimente com bolinhas de papel e conte quantas ele comeu.",
 apr="Contagem e motricidade (abrir e fechar)."),
dict(n=68, t="Coruja Sabida", c=6, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Tinta marrom", "Papel colorido", "Canetinha", "Cola"],
 pec=["Orelhinhas: dobre a borda de cima do rolo para dentro dos dois lados", "2 olhos: círculos de 3 cm com círculo preto de 1,5 cm", "Bico: triângulo de 1,5 cm", "2 asas: gotas de 6 cm", "Penas da barriga: meias-luas de 1 cm"],
 pas=["Dobre o topo do rolo para formar as orelhinhas.", "Pinte o rolo de marrom.", "Cole os olhões e o bico.", "Cole as asas dos lados.", "Cole as peninhas na barriga, uma sobre a outra."],
 brinca="Brinque de 'coruja da noite': apague a luz e a coruja com a lanterna encontra os objetos.",
 apr="Animais noturnos e sobreposição (colagem em camadas)."),
dict(n=69, t="Urso Dorminhoco", c=6, i="3+", tm="25 min", d=1,
 mat=["1 caixa pequena ou rolo de papel", "Tinta marrom", "Papel bege", "Retalho de pano (cobertor)", "Cola"],
 pec=["Cabeça: círculo de 6 cm", "2 orelhas: círculos de 2,5 cm", "Focinho: oval bege de 3 x 2 cm", "Barriga: oval bege de 5 x 6 cm"],
 pas=["Pinte o corpo de marrom.", "Cole a barriga bege.", "Monte a cabeça com orelhas e focinho.", "Desenhe olhinhos fechados (dormindo).", "Faça uma caminha numa caixa e cubra com o pano."],
 brinca="Explique a hibernação: o urso dorme o inverno inteiro. Brinque de acordar o urso bem devagar.",
 apr="Estações do ano e noções de natureza."),
dict(n=70, t="Pinguim Elegante", c=6, i="3+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "Tinta preta", "Papel branco e laranja", "Olhinhos", "Cola"],
 pec=["Barriga: oval branca de 6 x 8 cm", "Bico: triângulo laranja de 2 cm", "2 pés: gotas laranja de 2 cm", "2 asas: gotas pretas de 5 cm"],
 pas=["Pinte o rolo de preto.", "Cole a barriga branca na frente.", "Cole o bico e os olhinhos.", "Cole as asas dos lados e os pés embaixo.", "Faça uma gravatinha-borboleta de papel, se quiser."],
 brinca="Ande como pinguim com uma bolinha entre os joelhos sem deixar cair!",
 apr="Equilíbrio, polos e animais do frio."),
# ---------------- DINOSSAUROS (c=7) ----------------
dict(n=71, t="Tiranossauro Rex", c=7, i="4+", tm="40 min", d=2,
 mat=["1 caixa de creme dental", "1 rolo de papel higiênico", "Papelão fino", "Tinta verde", "Papel branco", "Cola quente (uso do adulto)"],
 pec=["Cabeça: perfil de 10 x 6 cm com boca aberta", "Dentes: zigue-zague branco de 6 cm", "2 bracinhos: tiras de 3 x 1 cm", "Rabo: triângulo comprido de 15 x 5 cm", "2 pernas fortes: pedaços de 4 cm do rolo"],
 pas=["Pinte o corpo, a cabeça e o rabo de verde.", A+"Cole as pernas (rolo cortado) embaixo do corpo.", A+"Cole a cabeça na frente, um pouco para cima.", "Cole os dentes na boca e os bracinhos pequenos.", "Cole o rabo atrás e desenhe as escamas."],
 brinca="Faça uma pegada gigante de papel no chão e siga o rastro do T-Rex pela casa.",
 apr="Proporção (braço pequeno, cabeça grande) e pré-história."),
dict(n=72, t="Tricerátops de Três Chifres", c=7, i="4+", tm="40 min", d=2,
 mat=["1 pote de iogurte ou garrafa PET pequena", "4 tampinhas", "Papelão fino", "Tinta", "Cola quente (uso do adulto)"],
 pec=["Escudo da cabeça: meia-lua de 10 cm com bolinhas desenhadas", "3 chifres: cones pequenos ou triângulos de 3 cm", "Rabo: triângulo de 8 x 3 cm"],
 pas=["Pinte o pote (o corpo) e as peças.", A+"Cole as 4 tampinhas embaixo como patas.", "Cole o escudo na frente, em pé.", "Cole os 3 chifres: 2 no escudo e 1 no nariz.", "Cole o rabo e desenhe os olhos."],
 brinca="Conte os chifres e os dedos: quantos chifres têm 3 tricerátops juntos?",
 apr="Contagem e formas (triângulo e meia-lua)."),
dict(n=73, t="Estegossauro de Placas", c=7, i="4+", tm="40 min", d=2,
 mat=["1 caixa de creme dental ou rolo de papel", "Papelão de caixa de cereal", "4 rolinhos para as patas", "Tinta verde e laranja", "Cola"],
 pec=["Placas das costas: 7 losangos de tamanhos de 3 a 6 cm", "Espinhos do rabo: 4 triângulos de 2 cm", "Cabeça pequena: oval de 4 x 3 cm"],
 pas=["Pinte o corpo de verde.", "Pinte as placas de laranja.", A+"Faça um corte fino no alto do corpo e encaixe as placas em fila, das menores às maiores.", "Cole a cabeça pequena, as patas e os espinhos no rabo.", "Desenhe os olhos."],
 brinca="Organize as placas do menor para o maior e depois do maior para o menor.",
 apr="Seriação por tamanho (ordenar)."),
dict(n=74, t="Pterodáctilo Voador", c=7, i="4+", tm="30 min", d=1,
 mat=["Papelão fino de caixa de cereal", "1 palito de churrasco sem ponta", "Barbante", "Tinta", "Cola"],
 pec=["Asas: formato de 'M' de 30 x 12 cm", "Cabeça: triângulo comprido de 8 cm com crista de 3 cm", "Corpo: gota de 10 cm"],
 pas=["Desenhe as asas, a cabeça e o corpo no papelão.", A+"Recorte as peças.", "Pinte e desenhe as veias das asas.", "Cole o corpo e a cabeça no meio das asas.", A+"Faça um furinho nas costas e pendure com barbante."],
 brinca="Balance o barbante e faça o pterodáctilo planar sobre a 'terra dos dinossauros'.",
 apr="Simetria e movimento (planar)."),
dict(n=75, t="Braquiossauro Pescoção", c=7, i="4+", tm="35 min", d=2,
 mat=["1 garrafa PET pequena ou caixa de leite", "1 rolo de papel toalha", "4 rolinhos para as patas", "Tinta verde ou azul", "Cola quente (uso do adulto)"],
 pec=["Pescoço: rolo de papel toalha inteiro", "Cabeça: oval de 5 x 3 cm", "Rabo: cone de meio círculo de 12 cm"],
 pas=["Pinte todas as peças.", A+"Cole o pescoço inclinado para cima na frente do corpo.", "Cole a cabeça na ponta do pescoço.", A+"Cole as patas embaixo e o rabo atrás.", "Desenhe manchas e olhinhos."],
 brinca="O braquiossauro come folhas do alto: coloque folhas de papel em cima dos móveis para ele 'comer'.",
 apr="Alto e baixo, alimentação dos animais (herbívoro)."),
dict(n=76, t="Ovo de Dinossauro Surpresa", c=7, i="3+", tm="30 min + secagem", d=1,
 mat=["1 bexiga", "Jornal picado", "Cola branca com água", "Tinta", "1 dinossauro pequeno de brinquedo ou feito de papel"],
 pec=["Casca: 2 camadas de papel machê em volta da bexiga", "Abertura: corte em zigue-zague de 6 cm (depois de seco)"],
 pas=["Encha a bexiga pequena e cubra com 2 camadas de jornal e cola.", "Espere secar por um dia.", "Pinte o ovo com pintinhas.", A+"Estoure a bexiga por dentro e faça um corte em zigue-zague.", "Coloque o dinossauro dentro e feche com um pedacinho de fita."],
 brinca="Esconda o ovo e a criança 'choca' e abre para descobrir qual dinossauro nasceu.",
 apr="Paciência, surpresa e ciclo de vida."),
dict(n=77, t="Fóssil para Escavar", c=7, i="5+", tm="40 min", d=2,
 mat=["1 caixa de sapato", "Palitos de picolé ou cotonetes (os 'ossos')", "Papelão branco", "Areia, farinha ou arroz cru", "1 pincel e 1 colher"],
 pec=["Esqueleto: crânio de 6 cm, 10 palitos como costelas e 1 tira de 20 cm como coluna"],
 pas=["Monte o esqueleto do dinossauro colando os palitos no papelão branco.", "Coloque o esqueleto no fundo da caixa.", "Cubra tudo com areia, farinha ou arroz.", "Dê à criança o pincel e a colher: ela é a paleontóloga!"],
 brinca="Escave devagar com o pincel, como os cientistas de verdade, e descubra o dinossauro.",
 apr="Paciência, ciência e controle de força."),
dict(n=78, t="Máscara de Dinossauro", c=7, i="4+", tm="35 min", d=2,
 mat=["1 prato de papel ou caixa de cereal", "Tinta verde", "Papel branco", "Elástico", "Cola"],
 pec=["Máscara: formato de focinho de 22 x 15 cm", "Dentes: zigue-zague branco na borda de baixo", "Buracos dos olhos: 2 círculos de 3 cm", "Espinhos: 4 triângulos de 3 cm em cima"],
 pas=["Desenhe a máscara no papelão.", A+"Recorte a máscara e os buracos dos olhos.", "Pinte de verde e cole os espinhos em cima.", "Cole os dentes na borda.", A+"Faça 2 furos nas laterais e prenda o elástico."],
 brinca="Desfile de dinossauros: cada um inventa o nome e o rugido do seu dino.",
 apr="Expressão e criatividade."),
dict(n=79, t="Vulcão em Erupção", c=7, i="5+", tm="45 min", d=2,
 mat=["1 garrafa PET pequena", "1 prato de papelão ou tampa de caixa (a base)", "Jornal e fita crepe", "Tinta marrom", "Vinagre, bicarbonato, detergente e corante (uso com o adulto)"],
 pec=["Montanha: jornal amassado em volta da garrafa, coberto com fita crepe", "Lava pintada: faixas vermelhas descendo do topo"],
 pas=["Prenda a garrafa aberta no centro da base.", "Faça a montanha em volta com jornal amassado e fita crepe.", "Pinte de marrom e desenhe a lava.", A+"Coloque 2 colheres de bicarbonato, detergente e corante dentro da garrafa.", A+"Na hora da erupção, despeje meio copo de vinagre e afaste as mãos."],
 brinca="Faça a contagem regressiva e veja a erupção! Faça do lado de fora ou em cima de uma bacia.",
 apr="Reação química simples, observação e causa e efeito."),
dict(n=80, t="Garras de Dinossauro", c=7, i="3+", tm="25 min", d=1,
 mat=["2 caixinhas pequenas (de remédio ou pasta de dente, cortadas) ou 2 copos de papel", "Papelão fino", "Tinta verde", "Cola"],
 pec=["Luva: caixinha onde entra a mão da criança", "3 garras por mão: triângulos de 4 cm", "Escamas: círculos de 1,5 cm"],
 pas=[A+"Prepare as caixinhas abertas de um lado para a mão entrar.", "Pinte de verde.", "Cole 3 garras na ponta de cada uma.", "Cole ou desenhe as escamas.", "Calce na mão e ruja!"],
 brinca="Com as garras, pegue bolinhas de papel e leve até a toca do dinossauro.",
 apr="Motricidade grossa e faz de conta."),
]
