A = "[ADULTO] "
P = [
# ---------------- ROBÔS E INVENÇÕES (c=8) ----------------
dict(n=81, t="Robô de Caixas", c=8, i="4+", tm="45 min", d=2,
 mat=["1 caixa de sapato (corpo)", "1 caixa menor (cabeça)", "4 rolos de papel higiênico (braços e pernas)", "Tampinhas coloridas", "Papel alumínio", "Cola quente (uso do adulto)"],
 pec=["Painel da barriga: retângulo de 8 x 6 cm com botões de tampinha", "2 olhos: tampinhas", "Antena: canudo com bolinha na ponta", "Garras: 2 formatos de 'C' de 4 cm"],
 pas=["Cubra as caixas com papel alumínio ou pinte de cinza.", A+"Cole a cabeça em cima do corpo.", A+"Cole 2 rolos nas laterais (braços) e 2 embaixo (pernas).", "Cole o painel e os botões na barriga.", "Cole os olhos, a antena e as garras.", "Dê um nome e um número de série para o robô."],
 brinca="Brinque de dar comandos: o robô só obedece se a ordem vier com 'por favor'!",
 apr="Montagem de partes, comando e sequência."),
dict(n=82, t="Máscara de Robô", c=8, i="4+", tm="35 min", d=2,
 mat=["1 caixa onde caiba a cabeça da criança", "Papel alumínio", "Tampinhas", "Canudos", "Fita crepe"],
 pec=["Visor dos olhos: retângulo de 14 x 4 cm", "Boca: grade de 8 x 3 cm desenhada", "2 antenas: canudos de 10 cm", "Orelhas: 2 tampas de pote"],
 pas=[A+"Recorte a abertura de baixo para a cabeça e o visor na altura dos olhos.", "Cubra com fita crepe as bordas cortadas.", "Cubra com papel alumínio.", "Cole as tampas de pote como orelhas e as tampinhas como botões.", "Cole as antenas no topo e desenhe a boca de grade."],
 brinca="Fale com voz de robô e ande como robô: devagar, dando giros de 90 graus.",
 apr="Expressão corporal, lateralidade e voz."),
dict(n=83, t="Braço Robótico de Canudos", c=8, i="7+", tm="60 min", d=3,
 mat=["Papelão fino", "5 canudos grossos", "Barbante ou linha grossa", "Fita adesiva", "Contorno da mão da criança"],
 pec=["Mão: contorno da mão da criança no papelão", "Canudos: 15 pedacinhos de 2 cm (3 por dedo)", "5 barbantes de 35 cm"],
 pas=["Contorne a mão da criança no papelão e recorte.", "Faça 2 vincos em cada dedo, nas 'juntas', dobrando levemente.", "Cole 3 pedacinhos de canudo em cada dedo, entre as juntas.", "Passe um barbante por dentro dos canudos de cada dedo.", "Prenda a ponta do barbante na ponta do dedo com fita.", "Puxe os barbantes: os dedos dobram como uma mão de verdade!"],
 brinca="Desafio: pegue um copo de papel usando só a mão robótica.",
 apr="Ciência (como funcionam os tendões) e engenharia."),
dict(n=84, t="Fantasia de Robô", c=8, i="4+", tm="60 min", d=2,
 mat=["1 caixa grande (onde caiba o tronco da criança)", "Papel alumínio ou tinta prata", "Tampinhas e botões", "Rolos de papel", "Fita crepe larga"],
 pec=["Buracos: 1 para a cabeça (18 cm) e 2 para os braços (12 cm)", "Painel: 15 x 10 cm com botões", "Medidor: meia-lua de 8 cm com ponteiro"],
 pas=[A+"Recorte os buracos da cabeça e dos braços e retire o fundo da caixa.", "Proteja as bordas com fita crepe.", "Cubra com papel alumínio ou pinte.", "Cole o painel, os botões e o medidor.", "Cole rolos como tubos nas laterais.", "Vista junto com a máscara de robô (projeto 82)."],
 brinca="Festa robô: música, dança robótica e desfile de fantasias.",
 apr="Autonomia (vestir-se) e criatividade."),
dict(n=85, t="Computador de Brinquedo", c=8, i="4+", tm="40 min", d=1,
 mat=["1 caixa de pizza pequena ou caixa de sapato com tampa", "Papel preto", "Tampinhas pequenas ou papel", "Canetinhas", "Cola"],
 pec=["Tela: retângulo de 18 x 12 cm", "Teclado: 30 quadradinhos de 1,5 cm com letras", "Mouse: tampinha grande"],
 pas=["Abra a caixa como um notebook: a tampa é a tela.", "Cole a tela e desenhe um jogo ou um desenho animado.", "Cole os quadradinhos com letras e números no teclado.", "Cole a tampinha do lado como mouse.", "Escreva o nome da criança na tela de 'boas-vindas'."],
 brinca="Brinque de escritório: digite o nome, mande 'e-mails' e faça reuniões com os bonecos.",
 apr="Letras, números e primeiros contatos com o teclado."),
dict(n=86, t="Controle de Videogame", c=8, i="4+", tm="30 min", d=1,
 mat=["Papelão firme", "Tampinhas coloridas", "Papel colorido", "Canetinhas", "Cola"],
 pec=["Controle: formato de 18 x 10 cm com as pontas arredondadas", "Direcional: cruz de 4 cm", "4 botões: tampinhas coloridas", "2 botões pequenos: retângulos de 1,5 x 0,7 cm"],
 pas=["Desenhe o formato do controle no papelão.", A+"Recorte o controle.", "Pinte ou cubra com papel.", "Cole a cruz do direcional do lado esquerdo.", "Cole as 4 tampinhas do lado direito e escreva letras nelas."],
 brinca="Videogame de verdade: um aperta os botões e o outro 'é o personagem' que pula, abaixa e corre.",
 apr="Direções (cima, baixo, direita, esquerda) e cooperação."),
dict(n=87, t="Câmera Fotográfica", c=8, i="4+", tm="30 min", d=1,
 mat=["1 caixa pequena (de chá ou remédio)", "1 rolo de papel higiênico ou tampa de pote", "Papel preto", "Barbante", "1 tampinha", "Cola"],
 pec=["Lente: rolo cortado de 4 cm ou tampa de pote", "Visor: quadrado de 2 x 2 cm", "Botão de disparo: tampinha", "Alça: barbante de 60 cm"],
 pas=["Cubra a caixa com papel preto.", "Cole a lente na frente.", A+"Recorte o visor atrás para a criança 'olhar' pela câmera.", "Cole o botão em cima.", A+"Faça 2 furinhos e prenda a alça de barbante."],
 brinca="Saia 'fotografando' coisas redondas, vermelhas ou macias. Depois ela desenha as 'fotos'.",
 apr="Observação, classificação e desenho."),
dict(n=88, t="Walkie-Talkie da Missão", c=8, i="4+", tm="30 min", d=1,
 mat=["2 caixinhas de remédio ou de suco", "2 canudos", "Tampinhas pequenas", "Papel alumínio", "Cola"],
 pec=["Antena: canudo de 8 cm", "Alto-falante: grade de 3 x 3 cm desenhada", "Botões: 3 tampinhas"],
 pas=["Cubra as 2 caixinhas com papel preto ou alumínio.", "Cole a antena em cima de cada uma.", "Desenhe o alto-falante com riscos.", "Cole os botões e escreva 'FALAR'.", "Faça o outro igual: são 2 rádios, um para cada."],
 brinca="Missão secreta: fale em código ('Águia chamando Formiga, câmbio!') de um cômodo para o outro.",
 apr="Comunicação, escuta e turnos de fala."),
dict(n=89, t="Relógio de Pulso", c=8, i="4+", tm="25 min", d=1,
 mat=["1 rolo de papel higiênico", "1 tampinha grande", "Papel branco", "Grampo bailarina", "Canetinhas", "Cola"],
 pec=["Pulseira: rolo cortado aberto no comprimento (encaixa no pulso)", "Mostrador: círculo de 4 cm com os números de 1 a 12", "2 ponteiros: tiras de 1,5 cm e 1 cm"],
 pas=["Corte o rolo aberto no comprimento para abraçar o pulso.", "Pinte a pulseira.", "Escreva os números de 1 a 12 no mostrador.", A+"Prenda os ponteiros no centro com o grampo bailarina.", "Cole o mostrador na tampinha e a tampinha na pulseira."],
 brinca="'Que horas são?' Mostre as horas de rotina: almoço, banho, dormir.",
 apr="Números até 12 e noção de tempo."),
dict(n=90, t="Máquina de Bolinhas", c=8, i="6+", tm="60 min", d=3,
 mat=["1 caixa de sapato", "1 pote transparente", "2 rolos de papel", "1 tira de papelão", "Bolinhas de papel ou pompons", "Cola quente (uso do adulto)"],
 pec=["Rampa interna: tira de 25 x 6 cm", "Saída: abertura de 5 x 5 cm na frente", "Botão: tampinha que puxa uma lingueta de 3 x 8 cm"],
 pas=[A+"Faça um buraco de 5 cm na tampa da caixa e cole o pote virado em cima, com a boca para baixo.", A+"Por dentro, cole a rampa inclinada descendo até a saída na frente.", A+"Recorte a saída na frente, embaixo.", "Crie uma lingueta de papelão que tampa a passagem: puxou, a bolinha desce.", "Decore como uma máquina de doces colorida."],
 brinca="Coloque uma 'moeda' de papel e ganhe uma bolinha. Quantas moedas para 5 bolinhas?",
 apr="Mecânica, gravidade e troca (dinheiro)."),
# ---------------- CASINHA DE BRINCAR (c=9) ----------------
dict(n=91, t="Fogãozinho de 4 Bocas", c=9, i="3+", tm="45 min", d=2,
 mat=["1 caixa de papelão média", "Papel preto", "4 tampinhas grandes", "1 tampa de pote", "Grampos bailarina", "Tinta branca ou prata"],
 pec=["4 bocas: círculos pretos de 10 cm com espiral vermelha desenhada", "Porta do forno: retângulo de 25 x 18 cm recortado em 3 lados", "Puxador: tira de 10 x 2 cm", "4 botões: tampinhas presas com grampo bailarina (giram)"],
 pas=["Pinte a caixa de branco ou prata.", "Cole as 4 bocas em cima.", A+"Recorte a porta do forno na frente, em 3 lados, para ela abrir para baixo.", "Cole o puxador na porta.", A+"Prenda os botões com grampo bailarina: eles giram de verdade!", "Coloque panelinhas e 'cozinhe'."],
 brinca="Restaurante da família: a criança anota o pedido e 'prepara' o prato.",
 apr="Rotina da casa, faz de conta e vocabulário dos alimentos."),
dict(n=92, t="Geladeira de Duas Portas", c=9, i="4+", tm="45 min", d=2,
 mat=["1 caixa de papelão alta", "Tampas de caixa ou papelão para prateleiras", "Tinta branca", "2 tiras de papelão para puxadores", "Embalagens vazias"],
 pec=["Porta do congelador: retângulo de cima (1/3 da altura)", "Porta da geladeira: retângulo de baixo (2/3 da altura)", "Prateleiras: tiras de papelão do tamanho do interior", "Puxadores: 2 tiras de 12 x 2 cm"],
 pas=[A+"Recorte as duas portas na frente da caixa, deixando um lado preso como dobradiça.", "Pinte tudo de branco.", "Cole as prateleiras por dentro.", "Cole os puxadores.", "Encha com embalagens vazias e ímãs desenhados na porta."],
 brinca="Organize a geladeira: frutas embaixo, bebidas na porta, congelados em cima.",
 apr="Classificação e organização."),
dict(n=93, t="Máquina de Lavar", c=9, i="4+", tm="40 min", d=2,
 mat=["1 caixa de papelão média (cubo)", "1 prato de papel ou tampa de pote grande", "Celofane transparente", "Tampinhas", "Tinta branca"],
 pec=["Porta redonda: círculo de 18 cm (abre com fita crepe)", "Visor: celofane", "Painel: faixa de 25 x 6 cm com botões e um mostrador"],
 pas=["Pinte a caixa de branco.", A+"Recorte o círculo da porta na frente, deixando um pedaço preso para abrir.", "Cole o celofane por dentro da porta.", "Cole o painel em cima com tampinhas como botões.", "Coloque roupinhas de boneca dentro."],
 brinca="Lavar, estender e dobrar as roupinhas das bonecas num varal de barbante.",
 apr="Tarefas da casa, dobrar e organizar."),
dict(n=94, t="Pia com Torneira", c=9, i="4+", tm="45 min", d=2,
 mat=["1 caixa de papelão média", "1 pote plástico raso (a cuba)", "1 rolo de papel toalha dobrado (torneira)", "2 tampinhas", "Papel alumínio"],
 pec=["Buraco da cuba: contorno do pote em cima da caixa", "Torneira: rolo curvado coberto com papel alumínio", "Registros: 2 tampinhas"],
 pas=[A+"Contorne o pote em cima da caixa e recorte o buraco.", "Encaixe o pote: ele é a cuba da pia.", "Cubra o rolo com papel alumínio e dobre em curva.", A+"Cole a torneira atrás da cuba e as tampinhas dos lados.", "Pinte a frente como um armário com portinhas."],
 brinca="Brinque de lavar a louça de brinquedo e secar com um paninho.",
 apr="Autonomia e colaboração nas tarefas de casa."),
dict(n=95, t="Micro-ondas", c=9, i="4+", tm="35 min", d=1,
 mat=["1 caixa de sapato", "Celofane ou plástico transparente", "Papel preto", "Tampinhas", "1 tampa de pote (prato giratório)"],
 pec=["Porta: retângulo de 18 x 10 cm (abre de lado)", "Janela: retângulo de 12 x 7 cm na porta", "Painel: 6 x 10 cm com números de 0 a 9"],
 pas=[A+"Recorte a porta na frente da caixa, deixando o lado esquerdo preso.", A+"Recorte a janela e cole o celofane.", "Cole o painel com os números do lado direito.", "Coloque a tampa de pote dentro como prato giratório.", "Desenhe o relógio digital."],
 brinca="'Esquente' a comida: digite 30 segundos e conte junto até terminar. Plim!",
 apr="Números de 0 a 9 e contagem de tempo."),
dict(n=96, t="Caixa Registradora", c=9, i="4+", tm="40 min", d=2,
 mat=["1 caixa de sapato", "1 caixinha pequena (a gaveta)", "Papel colorido", "Tampinhas", "Papel para notas e moedas"],
 pec=["Teclado: 12 quadrados de 2 cm com números de 0 a 9 e sinais", "Visor: retângulo de 8 x 3 cm", "Gaveta: caixinha que encaixa na frente", "Dinheirinho: notas de 8 x 4 cm e moedas de 2,5 cm (desenhe valores inventados)"],
 pas=[A+"Recorte uma abertura na frente da caixa para a gaveta deslizar.", "Encaixe a caixinha como gaveta.", "Cole o teclado inclinado em cima e o visor atrás.", "Faça as notas e moedas de brincadeira, com desenhos inventados.", "Separe a gaveta em espaços para notas e moedas."],
 brinca="Um é o caixa, o outro é o cliente: some os preços e dê o troco.",
 apr="Matemática (somar e dar troco) e valor do dinheiro."),
dict(n=97, t="Cafeteira de Brinquedo", c=9, i="4+", tm="35 min", d=2,
 mat=["1 caixa de leite", "1 copo plástico pequeno", "1 rolo de papel higiênico", "Tampinhas", "Tinta preta ou vermelha"],
 pec=["Base: caixa de leite em pé", "Recorte da frente: 7 x 8 cm para caber o copo", "Bico: rolo cortado de 3 cm", "Botões: 2 tampinhas"],
 pas=["Pinte a caixa.", A+"Recorte a abertura na frente, embaixo, para caber o copo.", "Cole o bico no teto da abertura.", "Cole os botões em cima.", "Coloque o copo embaixo do bico."],
 brinca="Cafeteria da família: sirva 'café com leite' e pergunte se o cliente quer com açúcar!",
 apr="Faz de conta, gentileza e servir o outro."),
dict(n=98, t="Liquidificador", c=9, i="4+", tm="30 min", d=1,
 mat=["1 garrafa PET pequena cortada ao meio", "1 caixinha pequena (a base)", "Tampinhas", "Papel colorido (frutas)", "Cola quente (uso do adulto)"],
 pec=["Copo: metade de cima da PET, virada, com a tampa", "Base: caixinha de 8 x 8 cm", "3 botões: tampinhas com números 1, 2 e 3", "Frutas: círculos e formatos de papel"],
 pas=[A+"Corte a garrafa ao meio e use a parte de cima virada como copo.", A+"Cole o copo em cima da caixinha.", "Pinte a base e cole os botões numerados.", "Recorte frutas de papel coloridas.", "Coloque as frutas dentro, tampe e 'bata' a vitamina."],
 brinca="Invente receitas de vitamina: 'banana com morango' e dê um nome para cada uma.",
 apr="Alimentação saudável, cores e números."),
dict(n=99, t="Torradeira com Torradas", c=9, i="3+", tm="30 min", d=1,
 mat=["1 caixa de lenço de papel ou caixa pequena", "Papelão bege", "Tinta prata ou vermelha", "1 tampinha", "Canetinha marrom"],
 pec=["2 aberturas em cima: 10 x 1,5 cm", "2 torradas: quadrados de 9 x 9 cm com a parte de cima arredondada", "Alavanca: tira de 3 x 1 cm na lateral"],
 pas=["Pinte a caixa.", A+"Recorte as 2 aberturas em cima.", "Pinte as bordas das torradas de marrom-claro, como se estivessem tostadas.", "Cole a alavanca e a tampinha (botão) na lateral.", "Coloque as torradas dentro."],
 brinca="Café da manhã de mentirinha: as torradas 'pulam' quando a criança bate palma!",
 apr="Rotina da manhã e atenção (esperar a hora certa)."),
dict(n=100, t="Mesa e Cadeira de Boneca", c=9, i="3+", tm="35 min", d=1,
 mat=["1 caixa de sapato pequena ou de creme dental", "Rolos de papel higiênico", "Palitos de picolé", "Retalho de tecido (toalha)", "Cola quente (uso do adulto)"],
 pec=["Tampo da mesa: tampa de caixa de 15 x 10 cm", "4 pés: rolos cortados de 6 cm", "Cadeiras: caixinhas de 5 x 5 cm com encosto de palito", "Toalha: tecido de 18 x 13 cm"],
 pas=[A+"Cole os 4 pés embaixo do tampo.", "Pinte a mesa.", A+"Monte as cadeiras colando o encosto de palitos em cada caixinha.", "Coloque a toalha de tecido.", "Faça pratinhos com tampinhas."],
 brinca="Chá da tarde das bonecas: cada convidada tem lugar marcado com plaquinha.",
 apr="Organização da mesa, contagem e convivência."),
]
