A = "[ADULTO] "
P = [
# ---------------- JOGOS E BRINCADEIRAS (c=10) ----------------
dict(n=101, t="Labirinto de Bolinha", c=10, i="4+", tm="40 min", d=2,
 mat=["1 tampa de caixa de sapato (ou caixa de pizza)", "Canudos ou tiras de papelão", "1 bolinha de gude ou bolinha de papel alumínio", "Canetinhas", "Cola quente (uso do adulto)"],
 pec=["Paredes: tiras de papelão de 1,5 cm de altura em vários comprimentos (3 a 20 cm)", "Largada e chegada: 2 círculos de 3 cm", "Buracos-armadilha (opcional): 2 círculos de 3 cm recortados no fundo"],
 pas=["Desenhe o caminho do labirinto a lápis no fundo da tampa.", A+"Cole as paredes em cima do desenho.", "Marque a largada e a chegada.", A+"Se quiser dificultar, recorte buracos-armadilha.", "Coloque a bolinha na largada e incline a caixa com as duas mãos."],
 brinca="Cronometre: quem leva a bolinha até a chegada mais rápido sem cair nas armadilhas?",
 apr="Coordenação das duas mãos, planejamento e concentração."),
dict(n=102, t="Pista de Carrinhos com Rampas", c=10, i="4+", tm="45 min", d=2,
 mat=["Rolos de papel toalha cortados ao meio no comprimento", "Tiras de papelão", "Fita crepe", "Caixas para dar altura", "Carrinhos pequenos"],
 pec=["Canaletas: rolos cortados ao meio no comprimento", "Rampa principal: tira de papelão de 60 x 10 cm com bordas dobradas de 2 cm", "Chegada: faixa quadriculada de 10 x 3 cm"],
 pas=[A+"Corte os rolos ao meio no comprimento para virarem canaletas.", "Dobre as bordas da rampa principal para os carros não caírem.", "Prenda a rampa na parede ou no sofá com fita crepe.", "Emende as canaletas com fita, fazendo curvas e descidas.", "Marque a linha de chegada."],
 brinca="Campeonato: cada carrinho desce 3 vezes e a criança anota quem chegou mais longe.",
 apr="Física (inclinação e velocidade), anotar e comparar."),
dict(n=103, t="Pinball de Mesa", c=10, i="6+", tm="60 min", d=3,
 mat=["1 tampa de caixa grande ou caixa de pizza", "Tampinhas e rolos cortados (obstáculos)", "2 palitos de picolé", "2 grampos bailarina", "Elástico", "1 bolinha de gude"],
 pec=["2 batedores: palitos de picolé presos com grampo bailarina (giram)", "Obstáculos: 6 anéis de rolo de 2 cm de altura", "Pontuação: números escritos em cada obstáculo"],
 pas=["Apoie um lado da caixa num livro, para ela ficar inclinada.", A+"Prenda os 2 batedores embaixo com grampos bailarina, perto da borda.", A+"Cole os anéis de rolo espalhados no meio da caixa.", "Escreva pontos em cada anel: 10, 20, 50…", "Solte a bolinha no alto e use os batedores para não deixar ela cair."],
 brinca="Some os pontos de cada partida e registre o recorde da família.",
 apr="Reflexo, soma e registro de pontos."),
dict(n=104, t="Jogo da Velha Gigante", c=10, i="4+", tm="30 min", d=1,
 mat=["1 pedaço grande de papelão (40 x 40 cm)", "10 tampinhas ou círculos de papelão", "Tinta de 2 cores", "Fita isolante ou canetinha grossa"],
 pec=["Tabuleiro: quadrado de 40 x 40 cm dividido em 9 casas", "5 peças 'X' e 5 peças 'O' de 8 cm"],
 pas=["Desenhe as 2 linhas verticais e as 2 horizontais no tabuleiro.", "Recorte as 10 peças no papelão.", "Pinte os X de uma cor e os O de outra.", "Decore as bordas do tabuleiro."],
 brinca="Campeonato em família: melhor de 5 partidas, com placar escrito.",
 apr="Estratégia, esperar a vez e lidar com vitória e derrota."),
dict(n=105, t="Basquete de Mesa", c=10, i="5+", tm="40 min", d=2,
 mat=["1 caixa de sapato", "1 rolo de papel higiênico", "1 copo de papel pequeno", "Palitos de picolé", "Elástico", "Bolinhas de papel alumínio"],
 pec=["Tabela: retângulo de 12 x 9 cm", "Cesta: copo de papel com o fundo recortado", "Catapulta: 2 palitos com uma tampinha na ponta, presos com elástico"],
 pas=[A+"Cole a tabela em pé em uma das pontas da caixa e o copo sem fundo como cesta.", "Monte a catapulta: prenda 2 palitos com elástico e cole uma tampinha na ponta.", "Faça bolinhas de papel alumínio.", "Coloque a bolinha na tampinha, aperte e solte!", "Pinte a quadra e as linhas."],
 brinca="Cada cesta vale 2 pontos; de longe vale 3. Quem faz 10 pontos primeiro?",
 apr="Força e mira (controle motor) e soma."),
dict(n=106, t="Boliche de Rolinhos", c=10, i="3+", tm="30 min", d=1,
 mat=["10 rolos de papel higiênico", "Tintas coloridas", "1 bola pequena", "Canetinhas"],
 pec=["Números: escreva de 1 a 10 nos rolos", "Carinhas: olhos e boca em cada pino"],
 pas=["Pinte cada rolo de uma cor.", "Escreva um número em cada pino, de 1 a 10.", "Desenhe carinhas engraçadas.", "Arrume os pinos em triângulo: 4, 3, 2, 1."],
 brinca="Some os números dos pinos derrubados em cada jogada.",
 apr="Números, soma e mira."),
dict(n=107, t="Pescaria com Varinha", c=10, i="3+", tm="40 min", d=1,
 mat=["1 caixa de sapato (o lago)", "Papelão fino", "Clipes", "1 ímã de geladeira pequeno", "1 palito de churrasco sem ponta ou lápis", "Barbante"],
 pec=["10 peixes: formatos de peixe de 6 a 8 cm", "Números de pontos em cada peixe (1 a 5)", "Varinha: palito + barbante de 40 cm + ímã na ponta"],
 pas=["Pinte o fundo da caixa de azul.", "Recorte e pinte os 10 peixes.", "Escreva os pontos em cada peixe.", "Prenda um clipe na boca de cada peixe.", A+"Amarre o barbante no palito e cole o ímã bem firme na ponta."],
 brinca="Pescaria de festa junina em casa: quem somar mais pontos ganha.",
 apr="Magnetismo, coordenação olho-mão e contagem."),
dict(n=108, t="Jogo de Argolas", c=10, i="4+", tm="35 min", d=1,
 mat=["1 caixa de ovos ou pedaço de papelão como base", "5 rolos de papel higiênico", "5 pratos de papel", "Tintas coloridas", "Cola quente (uso do adulto)"],
 pec=["Argolas: pratos de papel com o centro recortado (anel de 3 cm de largura)", "Pinos: rolos em pé, cada um com uma cor e pontuação"],
 pas=[A+"Cole os rolos em pé na base, com distância de 10 cm entre eles.", "Pinte cada pino de uma cor e escreva a pontuação.", A+"Recorte o centro dos pratos para fazer as argolas.", "Pinte as argolas.", "Marque no chão a linha de arremesso."],
 brinca="Arremesse as argolas: vale mais pontos acertar o pino mais distante.",
 apr="Mira, noção de distância e soma."),
dict(n=109, t="Cofre com Segredo", c=10, i="6+", tm="45 min", d=3,
 mat=["1 caixa de sapato com tampa", "3 tampas de pote", "3 grampos bailarina", "Papel colorido", "Canetinhas"],
 pec=["3 discos de segredo: tampas de pote com números de 0 a 9 em volta", "Setinhas: 3 triângulos de 1 cm", "Fenda para moedas: 4 x 0,5 cm"],
 pas=["Escreva os números de 0 a 9 em volta de cada tampa de pote.", A+"Prenda as 3 tampas na frente da caixa com grampos bailarina (elas giram).", "Cole uma setinha em cima de cada disco.", A+"Recorte a fenda para moedas em cima.", "Pinte como um cofre e defina a senha secreta."],
 brinca="Esconda pistas pela casa: cada pista revela um número da senha do cofre.",
 apr="Números, memória e raciocínio lógico."),
dict(n=110, t="Quebra-Cabeça Gigante", c=10, i="3+", tm="40 min", d=1,
 mat=["1 pedaço grande de papelão liso (caixa aberta)", "Tintas ou canetinhas", "Lápis", "Tesoura (uso do adulto)"],
 pec=["Tabuleiro: 40 x 30 cm", "Peças: 6 peças (3 anos), 12 peças (5 anos) ou 20 peças (7 anos), com cortes em ondas"],
 pas=["A criança desenha e pinta uma cena grande no papelão.", "Deixe secar bem.", "Vire e desenhe as linhas das peças a lápis, com curvas.", A+"Recorte as peças.", "Guarde num saquinho ou numa caixa."],
 brinca="Monte, desmonte e troque de quebra-cabeça com a família. Quanto tempo leva para montar?",
 apr="Percepção visual, paciência e resolução de problemas."),
# ---------------- MÚSICA E ARTE (c=11) ----------------
dict(n=111, t="Violão de Elásticos", c=11, i="4+", tm="40 min", d=2,
 mat=["1 caixa de lenço de papel (com abertura) ou caixa de sapato", "1 rolo de papel toalha (braço)", "5 elásticos de tamanhos diferentes", "2 lápis", "Cola quente (uso do adulto)"],
 pec=["Boca do violão: círculo de 8 cm (se a caixa não tiver abertura)", "Cavaletes: 2 lápis atravessados (um de cada lado do buraco)", "Braço: rolo de papel toalha"],
 pas=[A+"Recorte a boca do violão, se a caixa não tiver abertura.", "Pinte e decore o violão.", A+"Cole o rolo na ponta da caixa como braço.", "Estique os elásticos em volta da caixa, passando por cima da boca.", "Coloque os lápis embaixo dos elásticos, um de cada lado do buraco."],
 brinca="Toque cada elástico: qual faz som mais grosso? E mais fino? Invente uma música.",
 apr="Sons graves e agudos, ritmo e experimentação."),
dict(n=112, t="Bateria de Latas e Caixas", c=11, i="3+", tm="35 min", d=1,
 mat=["3 caixas ou latas de tamanhos diferentes (com tampa)", "2 tampas de panela velhas ou pratos de alumínio (pratos da bateria)", "2 colheres de pau ou lápis com bolinha de massinha", "Fita crepe", "Tinta"],
 pec=["Tambores: 3 caixas de tamanhos diferentes com a tampa bem presa", "Baquetas: 2 colheres de pau ou lápis grossos"],
 pas=["Prenda bem as tampas das caixas com fita crepe: vira a 'pele' do tambor.", "Pinte cada tambor de uma cor.", "Arrume os tambores em semicírculo.", "Apoie os pratos em copos virados.", "Prenda as caixas com fita para não saírem do lugar."],
 brinca="Imite ritmos: o adulto toca 'tum-tum-pá' e a criança repete. Depois invertam!",
 apr="Ritmo, memória auditiva e coordenação."),
dict(n=113, t="Chocalho Colorido", c=11, i="2+", tm="20 min", d=1,
 mat=["1 rolo de papel higiênico ou garrafinha de iogurte", "Arroz, feijão ou milho", "Papel colorido", "Fita adesiva larga", "Fitas de cetim ou tiras de papel"],
 pec=["2 tampas: círculos de 7 cm (feche as pontas do rolo)", "Fitinhas: 4 tiras de 20 cm"],
 pas=["Feche uma ponta do rolo com o círculo e fita adesiva.", "Coloque um punhado de arroz ou feijão.", "Feche a outra ponta muito bem.", "Cubra com papel colorido.", "Cole as fitinhas nas pontas."],
 brinca="Faça chocalhos com grãos diferentes: qual faz o som mais alto? Adivinhe de olhos fechados.",
 apr="Percepção sonora e comparação."),
dict(n=114, t="Piano de Teclas", c=11, i="4+", tm="40 min", d=2,
 mat=["1 caixa de sapato comprida ou caixa de cereal deitada", "Papel branco e preto", "Canetinhas", "Cola"],
 pec=["8 teclas brancas: 4 x 12 cm", "5 teclas pretas: 2 x 7 cm", "Notas: DÓ, RÉ, MI, FÁ, SOL, LÁ, SI, DÓ escritas nas teclas brancas"],
 pas=["Cubra a caixa com papel preto.", "Cole as teclas brancas lado a lado, com espacinho entre elas.", "Cole as teclas pretas em grupos de 2 e 3 por cima.", "Escreva as notas nas teclas brancas.", "Faça uma partitura colorida: cada nota tem uma cor."],
 brinca="Cante as notas enquanto aperta as teclas: dó, ré, mi… e crie a primeira música da criança.",
 apr="Notas musicais, sequência e memória."),
dict(n=115, t="Teatro de Fantoches", c=11, i="4+", tm="60 min", d=2,
 mat=["1 caixa de papelão grande", "Retalhos de pano ou papel crepom (cortinas)", "Palitos de picolé", "Papel para os personagens", "Tinta"],
 pec=["Palco: abertura de 30 x 20 cm na frente da caixa", "Cortinas: 2 retângulos de 18 x 25 cm", "Placa: TEATRO em 25 x 5 cm", "Fantoches: 4 personagens de 8 cm colados em palitos"],
 pas=[A+"Recorte a abertura do palco na frente e retire o fundo da caixa.", "Pinte a caixa e decore com estrelas.", "Cole as cortinas dos lados do palco.", "Cole a placa em cima.", "Desenhe, recorte e cole cada personagem num palito."],
 brinca="Apresente uma peça para a família com ingresso desenhado e aplausos no final!",
 apr="Narrativa, oralidade, criatividade e autoconfiança."),
dict(n=116, t="Cavalete de Pintura", c=11, i="4+", tm="40 min", d=2,
 mat=["1 caixa de papelão média", "Prendedores de roupa", "Folhas de papel", "1 tampa de pote (paleta)", "Fita crepe"],
 pec=["Cavalete: caixa cortada em forma de triângulo (2 lados de 40 x 30 cm unidos em cima)", "Apoio do papel: tira de 30 x 4 cm dobrada em 'L'"],
 pas=[A+"Corte a caixa formando um triângulo em pé, como uma barraca.", "Prenda bem a parte de cima com fita crepe.", A+"Cole o apoio em 'L' na frente, embaixo.", "Prenda a folha com prendedores de roupa.", "Use a tampa de pote como paleta de tintas."],
 brinca="Exposição de arte: pendure as pinturas num varal e faça um 'vernissage' com suco.",
 apr="Expressão artística e mistura de cores."),
dict(n=117, t="Tear de Papelão", c=11, i="6+", tm="45 min", d=3,
 mat=["1 retângulo de papelão firme de 15 x 20 cm", "Lã de várias cores", "1 palito de picolé com furo (agulha) ou grampo de cabelo", "Fita crepe"],
 pec=["Tear: 15 x 20 cm com cortinhos de 1 cm a cada 1 cm nas duas bordas menores", "Agulha: palito de picolé com um furinho na ponta"],
 pas=[A+"Faça os cortinhos nas duas bordas menores.", "Passe a lã de um corte ao outro, de cima a baixo, bem esticada (é a urdidura).", "Amarre outra lã na agulha.", "Passe a agulha por cima e por baixo dos fios, alternando.", "Na volta, faça o contrário: onde passou por cima, agora passa por baixo.", "Troque as cores e empurre as linhas para ficarem juntinhas."],
 brinca="Faça tapetinhos para a casa das bonecas ou um marcador de página.",
 apr="Concentração, padrões (por cima e por baixo) e coordenação fina."),
dict(n=118, t="Caleidoscópio de Cores", c=11, i="6+", tm="40 min", d=2,
 mat=["1 rolo de papel toalha", "Papelão fino coberto com papel alumínio bem liso", "Plástico transparente", "Miçangas ou pedacinhos de papel celofane colorido", "Fita adesiva"],
 pec=["3 espelhinhos: tiras de 20 x 3 cm de papelão com alumínio, montadas em triângulo", "2 tampas: círculos de plástico transparente de 5 cm", "Visor: círculo de papel preto com um furo de 1 cm"],
 pas=["Monte um prisma triangular com as 3 tiras (o alumínio para dentro) e coloque dentro do rolo.", "Numa ponta, cole o visor com o furinho.", "Na outra ponta, cole um círculo transparente.", "Coloque as miçangas em cima e feche com o segundo círculo, formando uma 'caixinha'.", "Decore o rolo por fora."],
 brinca="Olhe contra a luz e gire: desenhe as formas que aparecem.",
 apr="Reflexo da luz, simetria e observação."),
dict(n=119, t="Binóculo de Explorador", c=11, i="3+", tm="20 min", d=1,
 mat=["2 rolos de papel higiênico", "Barbante", "Tinta ou papel colorido", "Fita adesiva", "Adesivos ou canetinhas"],
 pec=["Alça: barbante de 60 cm", "Ponte: tira de papelão de 4 x 3 cm entre os rolos"],
 pas=["Pinte ou cubra os 2 rolos.", "Cole os rolos lado a lado com a ponte no meio.", A+"Faça um furinho em cada rolo.", "Passe o barbante e dê nós: é a alça.", "Decore com adesivos."],
 brinca="Safári no quintal ou na praça: encontre 5 coisas verdes, 3 bichinhos e 1 nuvem engraçada.",
 apr="Observação, atenção e contato com a natureza."),
dict(n=120, t="Marionete Articulada", c=11, i="6+", tm="60 min", d=3,
 mat=["Papelão fino", "6 grampos bailarina", "Barbante ou linha", "2 palitos de picolé (controle)", "Tinta e canetinhas"],
 pec=["Cabeça: círculo de 6 cm", "Corpo: retângulo de 8 x 10 cm", "Braços: 4 tiras de 5 x 1,5 cm", "Pernas: 4 tiras de 6 x 2 cm", "Controle: 2 palitos colados em cruz"],
 pas=["Desenhe e recorte todas as peças do boneco.", "Pinte o rosto e a roupa.", A+"Una as peças nas 'juntas' com grampos bailarina (ombros, cotovelos, quadril, joelhos).", A+"Amarre linhas nas mãos, nos joelhos e na cabeça.", "Prenda a outra ponta das linhas no controle em cruz.", "Mexa o controle e faça a marionete andar e dançar."],
 brinca="Faça a marionete apresentar o teatro de fantoches (projeto 115)!",
 apr="Coordenação fina, articulações do corpo e narrativa."),
]
